### ISSUE TITLE
"All Access required" when I have all access

### ISSUE THREAD

**Issue by stevesbrain** [mopidy/mopidy-gmusic#101]
Hi there,

Added in my Google account, using device password (because of 2FA). Have tried both with and without using an existing mobile ID. I can stream any playlists, but the "radio stations" come up with a warning in the logs about "Google Play Music All Access is required for get_station_tracks()". I have the all access account already, so I'm just looking for some advice as to what may be causing this :)

**Comment by jodal** [comment]
Have you set the `gmusic/all_access` config value? See the readme for
details.

**Comment by stevesbrain** [comment]
Wow. Ultimate noodle brain. I somehow totally missed that part of the readme - so sorry to have wasted your time, but thank you for pointing out the solution nonetheless :)
