### ISSUE TITLE
Thumbsup?

### ISSUE THREAD

**Issue by lynnard** [mopidy/mopidy-gmusic#104]
There is a 'Promoted' playlist which seems to contain all the songs I've given a thumbsup to. However, I wasn't able to add any additional song into this playlist (ncmpcpp complains `MPD not implemented`).

**Comment by belak** [comment]
Right now the playlist portion of the codebase is probably the most lacking. There hasn't been any work on create/edit/deleting of playlists.

I assume the thumbs up playlist would just be a special case of that.

**Comment by belak** [comment]
I'm closing this in favor of #136
