### ISSUE TITLE
Problem with /usr/lib/python2.7... 

### ISSUE THREAD

**Issue by MelloXVI** [mopidy/mopidy-gmusic#106]
Hello, when i put Mopidy in a terminal, i have some errors ...

pi@raspberrypi:~ $ mopidy
INFO     Starting Mopidy 1.1.2
INFO     Loading config from builtin defaults
INFO     Loading config from /home/pi/.config/mopidy/mopidy.conf
WARNING  /home/pi/.config/mopidy/mopidy.conf has errors, line 84, 85 has been ignored.
INFO     Loading config from command line options
INFO     Disabled extension gmusic: pyasn1>=0.1.8 required, but found pyasn1 0.1.7 at /usr/lib/python2.7/dist-packages
INFO     Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, local
INFO     Disabled extensions: gmusic
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     Audio output set to "autoaudiosink"
INFO     Loaded 0 M3U playlists from /home/pi/.local/share/mopidy/m3u
INFO     Loaded 0 local tracks using json
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680

This :  Disabled extension gmusic: pyasn1>=0.1.8 required, but found pyasn1 0.1.7 at /usr/lib/python2.7/dist-packages
Why I can solved them ? Any idea ?

And for MPD et HTTP, who I can fix [::ffff ? 

And (again), what is pyasn1, and who i can fix them again ?

Thanks ! =)

**Comment by stonfute** [comment]
Just execute 

`pip install --upgrade pyasn1`
