### ISSUE TITLE
Problem with python

### ISSUE THREAD

**Issue by jcruzs** [mopidy/mopidy-gmusic#115]
_Hi Everybody_, 

I'm unable to run gmusic. This is what it shows in terminal.

> Disabled extension gmusic: (requests 2.9.1 (/usr/local/lib/python2.7/site-packages), 
> Requirement.parse('requests!=1.2.0,!=2.2.1,<2.8.0,>=1.1.0'), set(['gmusicapi']))

I'm in mac el capitan. 

**Thanks for any help!.**

**Comment by jodal** [comment]
This is an issue with gmusicapi, that'll be fixed by their next release. See #113 for details.
