### ISSUE TITLE
Library redesign ideas

### ISSUE THREAD

**Issue by belak** [mopidy/mopidy-gmusic#132]
This is more of a brainstorming issue, but as I rework the caching, I'd like to change how the library works to match the gmusic web UI.

- [x] "Various Artists" artist for compliations (it will only display compilation albums in your library)
- [x] Browse by Artist will display all albums for the artist
- [x] Browse by Album will display all tracks for the album
- [x] Browse by Tracks will display what it displays now
- [x] Browse by Artist will be based on the Album Artist, not the artist (to avoid some of the crazy artist collaboration names)

I'm open to other ideas and I'm even open to dropping these, but this is my current plan.

**Comment by jjok** [comment]
Will using Album Artist mean that compilations just come up as "Various Artists" (or whatever you've called it)? That would resolve #129, right?

**Comment by belak** [comment]
Yes, that's the current plan.

**Comment by belak** [comment]
All of these will be resolved by #131
