### ISSUE TITLE
Library Playlists do not appear

### ISSUE THREAD

**Issue by wilberking** [mopidy/mopidy-gmusic#138]
Did something change?  I used to see all the playlists that I had in my gmusic library in the "Playlists" view.  Now they're gone.

**Comment by belak** [comment]
Can you paste the output of `mopidy deps` and is there anything in the mopidy log which looks like an error?

**Comment by belak** [comment]
This has been inactive for over a month and I cannot reproduce this. If you are still experiencing it, please let me know (with more details) and I'd be happy to take a look.
