### ISSUE TITLE
Installing mopidy-gmusic breaks M3U backend on Raspbian

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy-gmusic#143]
As detailed in https://github.com/mopidy/mopidy/issues/1550, installing mopidy-gmusic v1.0.0 will break M3U playlist browsing.
Though this _may_ still be a bug in the `m3u` backend, my best guess so far is that this is somehow connected to the `future` module used by  `gmusicapi`.
So it would be interesting to know if this issue still exists with mopidy-gmusic 2.0.

**Comment by belak** [comment]
I'm not as familiar with the playlists portion... but I have an rPi lying around, so I might be able to test this at some point.

**Comment by tkem** [comment]
Thanks! You shouldn't need to do much with playlists; just placing an `.m3u` file in `$XDG_DATA_DIR/mopidy/m3u` or `/var/lib/mopidy/playlists` should trigger the error on Mopidy startup. Even an empty file should do.

**Comment by tkem** [comment]
Thanks! You shouldn't need to do much with playlists; just placing an `.m3u` file in `$XDG_DATA_DIR/mopidy/m3u` or `/var/lib/mopidy/playlists` should trigger the error on Mopidy startup. Even an empty file should do.

**Comment by tkem** [comment]
I fooled around a bit more, and indeed if I comment out the single line
```
import gmusicapi
```
M3U playlists work as expected. Needless to say, that somewhat defeats the purpose of mopidy-gmusic.
So this is most likely an issue related to `gmusicapi`.

**Comment by belak** [comment]
How hard would it be to try a newer version of mopidy-gmusic. There latest prerelease upgrades gmusicapi, so there's a chance that will fix it. I'll take a look when I can, but it seems like I should just fix a few of the bugs with the prerelease and get something out.

**Comment by tkem** [comment]
I already tried `pip --upgrade gmusicapi` but to no effect. Since I don't use gmusic myself, and my time is limited, too, I guess the best one could do is file a bug report with `gmusicapi` and/or `future` and let them sort it out.

**Comment by belak** [comment]
I'll try to keep my eye out for the next stable version... since it looks like this has been fixed upstream.

**Comment by tkem** [comment]
Great, thanks!
