### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by osleg** [mopidy/mopidy-gmusic#145]
Hello there.
I'd like to have some community help on brainstorming one long standing issue with Google Music which, like all google's issues, translated to everything and mopidy-gmusic as well.

If one uploading music to gmusic in encoding other than UTF8 - it will stay like this and everything will be giberish in any music player/web ui.

So my idea is to convert the names on fly to UTF8 to make it usable. The question is - how should I do it in a most efficient way.

As for now I see three options:
1. Using something like chardet to detect the encoding and if it's not UTF-8 - convert it. Though chardet might be not very reliable in some cases
2. Introducing new setting in which one can set the encoding he used to upload the files and gmusic will re-code on fly every file without even trying to detect the encoding by itself. Pros: No need in chardet. 
3. Use combination of both for detect encoding - if failed use encoding from setting

There is quite urelability with chardet in some cases, though those cases are introduced in playlist. More specifically - when the string is too short, like if we take name of band Б7 it will fail to detect this one letter.

**Comment by jjok** [comment]
There was a issue that someone raised that was very similar to this, but I can't find it at the moment. I'm not sure if it was in and extension or Mopidy itself.

**Comment by osleg** [comment]
Well this is not an issue with neither mopidy nor mopidy-gmusic as I stated
it before. It just (sorry for my english) annoying piece of shit that 
Google don't want to solve.

Therefore I want to implement it in gmusic plugin to make it more usable 
for those of us who had this unlucky moment of uploading music to gmusic
and now unable to fix it :)

**Comment by belak** [comment]
As far as I can tell, id3 tags don't support any encodings other than ISO-8859-1 or UTF-16, as specified in http://id3.org/id3v2.3.0#ID3v2_frame_overview.

It does leave the door open for other encodings, but I can see why Google would avoid supporting something not in the spec.

I'm not sure what it would be best to do here... I'd really like to avoid complicating the code if possible, but I can still see how this would be frustrating.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
