### ISSUE TITLE
Cannot load Mopidy-Gmusic

### ISSUE THREAD

**Issue by maxemillianian** [mopidy/mopidy-gmusic#150]
Hi,

I'm having trouble running Mopidy-Gmusic. I have tried intsalling via pip and also via pip3, (both of which show as successful), but, when I launch Mopidy, and source the config, the Gmusic extension doesn't show in the enabled or in the disabled extension list. 

Here's the part of my config file which relates to Mopidy-Gmusic:

[gmusic]
enabled = true
username = XXXX <my email
password = XXXX <generated Google app password
deviceid = XXXX <obtained via Android app

"pip freeze" shows "Mopidy-GMusic==1.0.0"

I'm running Arch .

Is there something obvious I'm missing here?

Thanks,
Max

**Comment by hanshuebner** [comment]
I had to install mopidy, Mopidy-Gmusic and the gmusicapi (https://github.com/simon-weber/gmusicapi) from source to make it work (it does!).

**Comment by jjok** [comment]
I don't think you should have to install `gmusicapi` specifically. I've never done that.

**Comment by jeffy1021** [comment]
I just installed Mopidy on a RPI0 on top of Jessie Lite.  After installing mopidy-gmusic, I ran **sudo mopidyctl config** and it showed that gmusic was disabled.  I checked the dependencies using **sudo mopidyctl deps** and it showed that the version of the pyasn1 package was not high enough.  I ran **sudo pip install --upgrade pyasn1** and all was well after that.

**Comment by j10sanders** [comment]
Hi @maxemillianian ,

Try using sudo for the pip install.  sudo pip install mopidy-gmusic.

Let me know if that works!

**Comment by db6edr** [comment]
@jeffy1021 running `sudo pip install --upgrade pyasn1` did the trick for me.

Raspbian Jessie installs an updated version of pyasn1, which is found and accepted by pip. Forcing an update pulls the latest - and working - version.

**Comment by belak** [comment]
If you're still having problems after trying the workarounds, feel free to reopen this
