### ISSUE TITLE
MDP timeout on song change

### ISSUE THREAD

**Issue by foosinn** [mopidy/mopidy-gmusic#151]
On every song change i get a short silence and mopidy seems to be completly stuck for some seconds.

All mpd clients i tried run in a short timeout. after they reconnect everything is back to normal until the next song switches.

In the log is only the new connection message after reconnect.

pip list:
http://ix.io/1wTW

Im running it in a virtual environ with the gi package linked.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
