### ISSUE TITLE
Ready for a v2.0.0 final release?

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-gmusic#152]
It seems 2.0.0rc1 has lots of nice improvements, and there has barely been any changes since the rc1 release in July. I see users complaining about broken features, like all access search, that has been fixed in develop and rc1.

@belak Are you comfortable with releasing the current develop branch as 2.0.0 final?

**Comment by belak** [comment]
It looks like I'm not going to be able to get to this tonight... here are the issues I'd like to make sure are addressed.

* #107 
* #139
* #143/#147

**Comment by jjok** [comment]
@belak Sorry. I haven't had a chance to investigate/fix the issues that I've raised.

**Comment by belak** [comment]
Not a problem. I haven't gotten around to it either, and some of those are things that I broke when I changed how things are cached locally.

**Comment by belak** [comment]
This is blocked by upstream until a new version of gmusicapi is released so we can get the fix for futures.

**Comment by belak** [comment]
Upstream has a new release so this is no longer blocked

**Comment by belak** [comment]
v2.0.0 has been released! :)

**Comment by jodal** [comment]
Great :-)
