### ISSUE TITLE
Playing stops after prolonged pause

### ISSUE THREAD

**Issue by ghost** [mopidy/mopidy-gmusic#160]
Tested on ncmpc through the mpd interface.

To replicate: pause a song for a decent period of time (>2 minutes?), unpausing will allow the song to play again for around 30 seconds and then the playing will stop, appearing to go to the beginning of the track in the unpaused state and frozen.

It's possible this is simply a buffering issue, however this never seems to happen with continuous playback.

**Comment by belak** [comment]
This is an issue with how gstreamer streams files... it doesn't grab the whole thing. I need to find a workaround to cache the whole song because the gmusicapi urls don't last very long.

**Comment by dwminer** [comment]
@belak Would it be easier to reload the track and seek to the point at which it was paused?

**Comment by belak** [comment]
Quite possibly. Sorry I haven't had any time to work on this. Pull requests would be welcome.

**Comment by belak** [comment]
This was originally done to fix another issue, but it should fix this as well. https://github.com/mopidy/mopidy/pull/1608

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
