### ISSUE TITLE
Support for multiple GMusic Users?

### ISSUE THREAD

**Issue by theFisher86** [mopidy/mopidy-gmusic#163]
I have mopidy setup for the whole family to use, however we also have the Google Music family plan.  If it wouldn't be too difficult I would really appreciate the ability to switch between pre-configured users.  I'm guessing the ability to add-in multiple user accounts wouldn't be that difficult but the method in which they switch (via the web interface preferably) would be the difficult part.  I've just started trying to learn python so I fiddles around a bit trying to add this functionality myself but I think it may be beyond my abilities.

**Comment by jjok** [comment]
I'm not sure this would be possible as you would need some kind of UI to let you switch between the different users, but users aren't really a concept that exists in Mopidy, or any of the extensions, at the moment. That means that clients/front-ends would have to add functionality which would only related to one specific extension.

**Comment by theFisher86** [comment]
That was the problem I was foreseeing as well. Figured I'd throw it out
there in case there was some functionality I want aware of

**Comment by jjok** [comment]
The only thing I can think of is that you could have a different config file per user, and you restart Mopidy every time you want to change user, loading the right config.

I expect someone else would know better than me though.

**Comment by theFisher86** [comment]
That's not a bad idea, I could just make a script for each login and run
that from the front end.

**Comment by kingosticks** [comment]
The ability to have Mopidy reload it's configuration has come up a few times in various different contexts but it's not currently possible (https://github.com/mopidy/mopidy/issues/502 and many others).  

There's also been some discussions on ways to integrate extra functionality through "core extensions" (https://github.com/mopidy/mopidy/issues/1100) which could then be exposed to frontends (https://github.com/mopidy/mopidy/issues/495).

Fundamental changes to Mopidy core, even seemingly simple ones, can be complicated. I'm not trying to put you off but it might be worth reading some of the existing issues on the subject before investing lots of time. It would definitely be worth trying to reignite the discussions in the old issues and ensure everyone is on the same page. 

For the time being, you're multiple config files approach might be easiest.

**Comment by dylandhall** [comment]
Could we simply install the gmusic plugin twice, registering it under a different name and looking for a different config? The plugin api would probably work just as well if the names were different, we'd just need it to look for a different config section per installation.

Does that sound possible?

**Comment by jjok** [comment]
Could you just change the extension so the top level folders are the users, then you click one of those, then you get the list of that users Artist, Albums, etc? You'd need to change the URI scheme to have a user ID or something as the first part.

**Comment by belak** [comment]
Sure, that's possible, just a bit of work...

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
