### ISSUE TITLE
Authorization issues after rebooting

### ISSUE THREAD

**Issue by dabluecaboose** [mopidy/mopidy-gmusic#167]
Hello!  I recently set up Mopidy to run on my machine and have been interfacing using ncmpcpp.  I've enjoyed using gmusic very much when I've been able to get it to work!  However, I've found that the setup keeps breaking when I reboot my computer.  After fixing it, which is never straightforward, it works fine until next reboot, even if I stop and restart the service.  I'm not even sure what specifically I've been doing that fixes it.  Sometimes I change the device ID to another valid device, once I changed the app-specific password.  Attached is my config and output from the mopidy status.

sudo systemctl status mopidy
```
Feb 15 19:24:56 BLU-2d mopidy[1310]:   File "/usr/local/lib/python2.7/dist-packa
Feb 15 19:24:56 BLU-2d mopidy[1310]:     raise ConnectionError(e, request=reques
Feb 15 19:24:56 BLU-2d mopidy[1310]: ConnectionError: HTTPSConnectionPool(host='
Feb 15 19:24:56 BLU-2d mopidy[1310]: ERROR    Actor died: GMusicBackend (urn:uui
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     Starting Mopidy core
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     Starting Mopidy frontends: MpdFron
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     MPD server running at [::ffff:127.
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     HTTP server running at [::ffff:127
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     Starting GLib mainloop
Feb 15 19:25:06 BLU-2d mopidy[1310]: INFO     New MPD connection from [::ffff:12
```

```
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[audio]
mixer = software
#mixer_volume = 
output = alsasink device=hw:0,0
#buffer_time = 

[local]
media_dir = /var/lib/mopidy/media

[m3u]
playlists_dir = /var/lib/mopidy/playlists

[gmusic]
enabled = true
username =xxxxxx
password =xxxxxx
bitrate = 160
deviceid = xxxxxx
all_access = false
refresh_library = 1440
refresh_playlists = 60
#radio_stations_in_browse = true
#radio_stations_as_playlists = false
#radio_stations_count = 
#radio_tracks_count = 25
```

Let me know if I left anything important out!  Thanks

**Comment by belak** [comment]
It looks like part of the traceback got cut off. Any chance you could provide a full one?

**Comment by dabluecaboose** [comment]
Whoops!  Didn't notice when I pasted that.  Here:

`Feb 15 19:24:56 BLU-2d mopidy[1310]:   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
Feb 15 19:24:56 BLU-2d mopidy[1310]:     raise ConnectionError(e, request=request)
Feb 15 19:24:56 BLU-2d mopidy[1310]: ConnectionError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7524058d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Feb 15 19:24:56 BLU-2d mopidy[1310]: ERROR    Actor died: GMusicBackend (urn:uuid:70620692-ed79-4329-942d-72d30c4948d8) stopped before handling the message
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     Starting Mopidy core
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend, GMusicScrobblerFrontend
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     MPD server running at [::ffff:127.0.0.1]:6600
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     HTTP server running at [::ffff:127.0.0.1]:6680
Feb 15 19:24:56 BLU-2d mopidy[1310]: INFO     Starting GLib mainloop
Feb 15 19:25:06 BLU-2d mopidy[1310]: INFO     New MPD connection from [::ffff:127.0.0.1]:46804
`

**Comment by belak** [comment]
Temporary failure in name resolution sounds like mopidy is starting before the network is available, so it's most likely an issue with the systemd unit file.

**Comment by dabluecaboose** [comment]
Well, I feel like a giant dingus.  It wasn't me messing around with the configs that was fixing things, it was stopping and restarting the service.  The issue is totally it trying to connect before the network.  Thanks so much for the prompt help!

**Comment by belak** [comment]
Any time! Glad to help.

Most unit files should have a method of specifying that they should start after network. http://unix.stackexchange.com/questions/126009/cause-a-script-to-execute-after-networking-has-started
