### ISSUE TITLE
Feeling lucky station

### ISSUE THREAD

**Issue by ivitivan** [mopidy/mopidy-gmusic#168]
Hi!

Thanks for the opportunity to have google music in my terminal and the ability to control it from other devices but I miss one thing: the "I'm Feeling Lucky" radio isn't updating like it does on google play web version. The content changes if I reload mopidy or if it refreshes playlists but the radio station doesn't change itself. It only changes if I hit the button "I'm feeling lucky" on web version. Is it expected behavior?
Also, it would be nice to have a full list of the settings in the readme or somewhere, because I only found information about `refresh_library` and `refresh_playlists` in the issues and source code.

**Comment by belak** [comment]
As far as I know, refresh_playlists will be called on a timer so it will be refreshed then.

It may be best to make browsing to it refresh the playlist... which should solve your problem.

**Comment by mkriegl** [comment]
I only see the I'm Feeling Lucky station without any content. No Playlists or Music is display in any other folder. gmusic scan seems to get no titels or playlists during restart. 
Any clue about that?

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
