### ISSUE TITLE
Install on not raspberry pi

### ISSUE THREAD

**Issue by disconnect5852** [mopidy/mopidy-gmusic#169]
Not just raspberry pis are the only arm linux devices, so not all have pip... how can i install this extension if i only have apt-get?

**Comment by kingosticks** [comment]
I'm not 100% sure what you are saying here but you can install pip from your package manager:
sudo apt-get install python-pip
Or:
curl https://bootstrap.pypa.io/get-pip.py | sudo python

A Google search would have shown you both of these options.

**Comment by disconnect5852** [comment]
Oh thanks, i thought that this pip is a package manager for raspberry pi.
