### ISSUE TITLE
Album art over https

### ISSUE THREAD

**Issue by jordanconway** [mopidy/mopidy-gmusic#170]
I'm serving my musicbox instance over ssl, but the album art always gets pulled in by http which makes things complain a bit.

I have a hacky workaround in library.py to just replace('http',https') for get_images(song) but it's not worthy of a PR. If I ever get around to figuring out a robust fix I'll send an actual PR, unless someone beats me to it, please be my guest!

**Comment by jjok** [comment]
Presumably the URLs just come from `gmusicapi`. Should the change be made there instead?

**Comment by belak** [comment]
As far as I know, the URLs come from google directly. gmusicapi is a pretty thin wrapper, so it would be a little odd to change the values that come back. I'll ask around and see what the gmusicapi maintainers think.

**Comment by belak** [comment]
It sounds like we'd have to make the translation here. It's odd that google returns http urls here.

Anyway, I'd be happy to accept a PR which does this translation.

**Comment by jjok** [comment]
I think this is no longer an issue. I'm using Iris and I'm getting artist images over HTTPS.

eg https://i.scdn.co/image/901ef67608802e5ce9a650a7980231bfe3b4f74b
