### ISSUE TITLE
Playing songs from 'promoted' playlist doesn't work

### ISSUE THREAD

**Issue by herrwusel** [mopidy/mopidy-gmusic#174]
As soon as I try to play songs from the liked playlist the song doesn't start.
This is the mopidy.log:
https://paste.debian.net/hidden/7e237643/

**Comment by foopod** [comment]
Can confirm this... having the same problem now.. get lines like this in the log....

2018-01-18 07:46:34,466 DEBUG [2797:GMusicBackend-12] mopidy_gmusic.library: Track not a library track u'gmusic:track:mnqvtagjqjibw4pwhq2n7d52ni

**Comment by adnidor** [comment]
I'm having the same problem, mopidy outputs: 
```
WARNING  Failed to get stream url for abc.
WARNING  Please ensure your deviceid is set correctly.
ERROR    Call to Google Music failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 32, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 90, in get_stream_url
    return self.api.get_stream_url(song_id, quality=quality)
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/usr/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 393, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStreamUrl: 404 Client Error: Not Found for url: https://mclients.googleapis.com/music/mplay?opt=med&songid=lahitgptmuz5sc3ga7oadpwgau&pt=e&slt=1525986664929&tier=aa&sig=r7dp9LFgXOG_eZpuuw2c6Kp0aPY&hl=en_US&dv=0&net=mob
(requests kwargs: {u'url': u'https://mclients.googleapis.com/music/mplay', u'headers': {u'X-Device-ID': u'abc', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'med', u'songid': u'abc', u'pt': u'e', u'slt': 'abc', u'tier': u'aa', u'sig': 'abcd', u'hl': u'en_US', u'dv': 0, u'net': u'mob'}, u'method': u'GET'})
(response was: u'<HTML>\n<HEAD>\n<TITLE>Not Found</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Not Found</H1>\n<H2>Error 404</H2>\n</BODY>\n</HTML>\n')
WARNING  Track is not playable: gmusic:track:lahitgptmuz5sc3ga7oadpwgau

```

**Comment by adnidor** [comment]
After investigating a bit, it seems that the problem is that the song in the "Promoted" playlist have an invalid URL.

Regular URL is: gmusic:track:Tglekchsp2yxx3fquu3kkypdbba
"Promoted" URL is: gmusic:track:glekchsp2yxx3fquu3kkypdbba

From looking at the code it seems that this is a bug in gmusicapi

**Comment by adnidor** [comment]
Just looked both at mopidy-gmusic as well as gmusicapi.

The core problem lies in the varying format of a track dict between get_all_songs() and get_promoted_songs().

The dict returned by get_all_songs() has the element "nid" set to "Twhatever", which is what mopidy-gmusic expects.
The dict returned by get_promoted_songs() has the element "nid" set to "whatever" but is processed by the same [function](https://github.com/mopidy/mopidy-gmusic/blob/d3b307ee9cee3a129fffab6b86f9790e0bc2575f/mopidy_gmusic/library.py#L496) as the other dict. 

This causes the ID in the URL for the "Promoted" song to miss the required "T" in the front.
