### ISSUE TITLE
Stream gets interrupted when a next song is played.

### ISSUE THREAD

**Issue by ErwinP** [mopidy/mopidy-gmusic#177]
Hi,

I'm streaming to a chromecast audio using icecast2, and always get a disconnection when a next song is about to be played. I assume that this is due to the fact that the stream still gets interrupted, despite that gappless playback should be enabled by default in version 2.1.0?

Is there anything that can be done about this?

Thank you in advance,
Erwin

**Comment by trygveaa** [comment]
Have you tried configuring a fallback stream, [as described here](https://docs.mopidy.com/en/latest/audio/?highlight=icecast#fallback-stream)?

**Comment by ErwinP** [comment]
No I didn't.. extremely stupid of me, I didn't scroll down enough to read that. I'm terribly sorry.

However, the stream still stops when changing tracks, despite the fallback. If I read correctly this time, this shouldn't be the case anymore?

Thank you in advance,
Erwin

**Comment by MaxG88** [comment]
Hi,
Have you ever found a solution to your problem? I'm having the same issue, and for now I managed to work around the issue by having Home Assistant seek to the last few seconds of a given track instead of going straight to the next track. However, this is not ideal...

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
