### ISSUE TITLE
I'm going crazy

### ISSUE THREAD

**Issue by eagj** [mopidy/mopidy-gmusic#178]
Hi i'm a newbie and i wanna use my raspberry with google music (family account) and when i launch mopidy always he says this:
INFO     Disabled extension gmusic: (pyasn1 0.3.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('pyasn1==0.1.7'), set(['oauth2client']))

I try thousand things, i search days and always the same, any help be good!

**Comment by kingosticks** [comment]
Please provide the output of `mopidy deps` as suggested in the [troubleshooting section of the documentation](https://docs.mopidy.com/en/latest/troubleshooting/#show-installed-dependencies).

**Comment by eagj** [comment]
Thanks at last i downgrade the pyas1 to 0.17 and now works, i dont know if is the best... but works!
I paste now the deps, ty for your help:

Executable: /usr/bin/mopidy
Platform: Linux-4.9.35-v7+-armv7l-with-debian-8.0
Python: CPython 2.7.9 from /usr/lib/python2.7
Mopidy: 2.1.0 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
  tornado>=3.2: 3.2.2 from /usr/lib/python2.7/dist-packages
Mopidy-GMusic: 2.0.0 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  cachetools>=1.0: 2.0.1 from /usr/local/lib/python2.7/dist-packages
  gmusicapi>=10.1: 10.1.2 from /usr/local/lib/python2.7/dist-packages
    protobuf>=3.0.0: 3.3.0 from /usr/local/lib/python2.7/dist-packages
      setuptools: 36.2.7 from /usr/local/lib/python2.7/dist-packages
      six>=1.9: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    mock>=0.7.0: 1.0.1 from /usr/local/lib/python2.7/dist-packages
    future: 0.15.2 from /usr/local/lib/python2.7/dist-packages
    validictory!=0.9.2,>=0.8.0: 1.0.0a2 from /usr/local/lib/python2.7/dist-packages
    mutagen>=1.34: 1.38 from /usr/local/lib/python2.7/dist-packages
    proboscis>=1.2.5.1: 1.2.6.0 from /usr/local/lib/python2.7/dist-packages
    six>=1.9.0: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    appdirs>=1.1.0: 1.4.0 from /usr/local/lib/python2.7/dist-packages
    oauth2client>=1.1: 1.4.1 from /usr/local/lib/python2.7/dist-packages
      pyasn1-modules==0.0.5: 0.0.5 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.4: 0.1.7 from /usr/local/lib/python2.7/dist-packages
      pyasn1==0.1.7: 0.1.7 from /usr/local/lib/python2.7/dist-packages
      six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      httplib2>=0.8: 0.9 from /usr/local/lib/python2.7/dist-packages
      rsa==3.1.4: 3.1.4 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.3: 0.1.7 from /usr/local/lib/python2.7/dist-packages
    MechanicalSoup>=0.4.0: 0.7.0 from /usr/local/lib/python2.7/dist-packages
      six>=1.4: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
      beautifulsoup4: 4.4.1 from /usr/local/lib/python2.7/dist-packages
    requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0: 2.4.3 from /usr/lib/python2.7/dist-packages
    gpsoauth>=0.2.0: 0.4.1 from /usr/local/lib/python2.7/dist-packages
      requests: 2.4.3 from /usr/lib/python2.7/dist-packages
      pycryptodomex>=3.0: 3.4.6 from /usr/local/lib/python2.7/dist-packages
    python-dateutil!=2.0,>=1.3: 2.2 from /usr/local/lib/python2.7/dist-packages
      six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    decorator>=3.3.1: 3.4.0 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
  setuptools: 36.2.7 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
    tornado>=3.2: 3.2.2 from /usr/lib/python2.7/dist-packages
Mopidy-Local-Images: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  uritools>=1.0: 2.0.0 from /usr/local/lib/python2.7/dist-packages
    ipaddress; python_version == "2.7": 1.0.18 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  setuptools: 36.2.7 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.1: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
    tornado>=3.2: 3.2.2 from /usr/lib/python2.7/dist-packages
GStreamer: 1.4.4.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.14.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec

**Comment by kingosticks** [comment]
I think this is because you have a really old version of oauth2client (1.4.1) which wants a specific version of pyasn1 (0.1.7). The most recent versions of oauth2client are happy with >0.1.7. You should probably update ```pip install -U oauth2client```.

**Comment by eagj** [comment]
Exactly is this, i upgrade the oauth2client, the pyasn1 and work perfect!
Many thanks mate, i paste my new deps if you see something weird tell me ;)

Executable: /usr/bin/mopidy
Platform: Linux-4.9.35-v7+-armv7l-with-debian-8.0
Python: CPython 2.7.9 from /usr/lib/python2.7
Mopidy: 2.1.0 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
  tornado>=3.2: 3.2.2 from /usr/lib/python2.7/dist-packages
Mopidy-GMusic: 2.0.0 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  cachetools>=1.0: 2.0.1 from /usr/local/lib/python2.7/dist-packages
  gmusicapi>=10.1: 10.1.2 from /usr/local/lib/python2.7/dist-packages
    protobuf>=3.0.0: 3.3.0 from /usr/local/lib/python2.7/dist-packages
      setuptools: 36.2.7 from /usr/local/lib/python2.7/dist-packages
      six>=1.9: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    mock>=0.7.0: 1.0.1 from /usr/local/lib/python2.7/dist-packages
    future: 0.15.2 from /usr/local/lib/python2.7/dist-packages
    validictory!=0.9.2,>=0.8.0: 1.0.0a2 from /usr/local/lib/python2.7/dist-packages
    mutagen>=1.34: 1.38 from /usr/local/lib/python2.7/dist-packages
    proboscis>=1.2.5.1: 1.2.6.0 from /usr/local/lib/python2.7/dist-packages
    six>=1.9.0: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    appdirs>=1.1.0: 1.4.0 from /usr/local/lib/python2.7/dist-packages
    oauth2client>=1.1: 4.1.2 from /usr/local/lib/python2.7/dist-packages
      pyasn1>=0.1.7: 0.3.2 from /usr/local/lib/python2.7/dist-packages
      pyasn1-modules>=0.0.5: 0.0.11 from /usr/local/lib/python2.7/dist-packages
        pyasn1==0.3.2: 0.3.2 from /usr/local/lib/python2.7/dist-packages
      six>=1.6.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      httplib2>=0.9.1: 0.10.3 from /usr/local/lib/python2.7/dist-packages
      rsa>=3.1.4: 3.4.2 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.3: 0.3.2 from /usr/local/lib/python2.7/dist-packages
    MechanicalSoup>=0.4.0: 0.7.0 from /usr/local/lib/python2.7/dist-packages
      six>=1.4: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
      beautifulsoup4: 4.4.1 from /usr/local/lib/python2.7/dist-packages
    requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0: 2.4.3 from /usr/lib/python2.7/dist-packages
    gpsoauth>=0.2.0: 0.4.1 from /usr/local/lib/python2.7/dist-packages
      requests: 2.4.3 from /usr/lib/python2.7/dist-packages
      pycryptodomex>=3.0: 3.4.6 from /usr/local/lib/python2.7/dist-packages
    python-dateutil!=2.0,>=1.3: 2.2 from /usr/local/lib/python2.7/dist-packages
      six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    decorator>=3.3.1: 3.4.0 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
  setuptools: 36.2.7 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
    tornado>=3.2: 3.2.2 from /usr/lib/python2.7/dist-packages
Mopidy-Local-Images: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  uritools>=1.0: 2.0.0 from /usr/local/lib/python2.7/dist-packages
    ipaddress; python_version == "2.7": 1.0.18 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  setuptools: 36.2.7 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.1: 2.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.4.3 from /usr/lib/python2.7/dist-packages
    tornado>=3.2: 3.2.2 from /usr/lib/python2.7/dist-packages
GStreamer: 1.4.4.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.14.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
