### ISSUE TITLE
Running as service missing dependency

### ISSUE THREAD

**Issue by micksabox** [mopidy/mopidy-gmusic#180]
Raspbian OS: "Raspbian GNU/Linux 9 (stretch)"

**Error Description:**
gmusic extension disabled when running mopidy as service, but is working when running directly from command line. Both configs are identical.

**Cause**
From the logs when running as a service:
`2017-10-12 15:24:06,530 INFO [1214:MainThread] mopidy.ext: Disabled extension gmusic: (pyasn1 0.1.9 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), set(['pyasn1-modules']))`

**Further Details**
When running `mopidy deps`, I get:
```
Mopidy-GMusic: 2.0.0 from /home/pi/.local/lib/python2.7/site-packages
  gmusicapi>=10.1: 10.1.2 from /home/pi/.local/lib/python2.7/site-packages
    oauth2client>=1.1: 4.1.2 from /home/pi/.local/lib/python2.7/site-packages  
        pyasn1<0.4.0,>=0.3.4: 0.3.7 from /home/pi/.local/lib/python2.7/site-packages
```
But `sudo mopidyctl deps` will say:
```
        pyasn1<0.4.0,>=0.3.4: not found
```

Hopefully I'm close enough to a quick resolution. Seems like I should just update pyasn1 but I have no idea how to do this - Python newbie here. Any help greatly appreciated. Thanks for making this available.

**Comment by micksabox** [comment]
Ok. I just had to do this.
`sudo easy_install pyasn1==0.3.7`
Will close.

**Comment by kingosticks** [comment]
It seems a little odd to have something installed in your pi user home directory that's then run as a service (running as user mopidy). Did you intentionally install it like that?

**Comment by micksabox** [comment]
Not sure. I tried following documentations instructions.

**Comment by jjok** [comment]
I feel like I encountered this, or something similar, a while ago. It was a missing dependency in one of the dependencies.

Is this a problem with `oauth2client`?

**Comment by kingosticks** [comment]
The issue here was that the files and dependencies were installed to the `pi` user home directory rather than the system path /usr/local/lib/python2.7/*-packages. This is fine when you run as that user but when you want to run as a service, that runs as a different user (`mopidy`) which will not see any files installed in /home/pi/.local/lib/python2.7/site-packages. If you want to run as a service, everything should be installed in the system path. Usually this means running `sudo pip install >blah>`.

**Comment by micksabox** [comment]
@jjok yes it was in the `oauth2client`.
@kingosticks yes my thoughts exactly. In that case, the documentation should indicate the need to prefix with `sudo` when intending to run as service.

**Comment by kingosticks** [comment]
The pip default has always been to try and install it system-wide which usually results in a permission error unless you have prefixed the command with sudo so then it's kind of obvious. I wonder what changed.
