### ISSUE TITLE
Gmusic skips next track from search

### ISSUE THREAD

**Issue by tort-dla-psa** [mopidy/mopidy-gmusic#182]
So, I search some artist in ncmcpp, load several albums from search to playlist, and sometimes when track ends, mopidy shows this error:

2017-11-06 20:26:56,661 WARNING [25596:Core-10] mopidy.core.tracklist: Track is not playable: gmusic:track:Tb5r4oohxwuwcsavvfm2s5dfb7u
2017-11-06 20:29:09,490 INFO [31019:MainThread] mopidy.__main__: Starting Mopidy 2.1.0
2017-11-06 20:29:09,526 INFO [31019:MainThread] mopidy.config: Loading config from builtin defaults
2017-11-06 20:29:09,527 INFO [31019:MainThread] mopidy.config: Loading config from /home/essir/.config/mopidy/mopidy.conf
2017-11-06 20:29:09,528 INFO [31019:MainThread] mopidy.config: Loading config from command line options
2017-11-06 20:29:09,593 INFO [31019:MainThread] mopidy.__main__: Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, local, gmusic
2017-11-06 20:29:09,593 INFO [31019:MainThread] mopidy.__main__: Disabled extensions: none
2017-11-06 20:30:36,037 ERROR [25596:GMusicBackend-7] mopidy_gmusic.session: HTTP request to Google Music failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 32, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 90, in get_stream_url
    return self.api.get_stream_url(song_id, quality=quality)
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/usr/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 383, in get_stream_url
    if song_id.startswith('T') and not self.is_subscribed:
  File "/usr/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 660, in __get__
    value = self.fget(inst)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 89, in is_subscribed
    res = self._make_call(mobileclient.Config)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 209, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/lib/python2.7/site-packages/gmusicapi/session.py", line 89, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/usr/lib/python2.7/site-packages/gmusicapi/session.py", line 234, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))
2017-11-06 20:30:36,040 WARNING [25596:Core-10] mopidy.core.tracklist: Track is not playable: gmusic:track:Tc3ob2lia3bokvfytx2bqotb24e

My config:

 [core]

cache_dir = ~/.config/mopidy/cache
config_dir = /etc/mopidy
data_dir = ~/.config/mopidy/data

[logging]
config_file = ~/.config/mopidy/logging.conf
debug_file = ~/.config/mopidy/mopidy-debug.log

[local]
data_dir = ~/.config/mopidy/local
media_dir = ~/files/Music
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt

[m3u]
playlists_dir = ~/.config/mopidy/playlists

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password = 
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist = 
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = 
timeout = 5000

[gmusic]
username = somesecretlogin
password = somesecretpassword
bitrate = 320
deviceid = somesecretid

Mopidy deps:

Executable:

 /usr/bin/mopidy
Platform: Linux-4.13.10-1-ARCH-x86_64-with-glibc2.2.5
Python: CPython 2.7.14 from /usr/lib/python2.7
Mopidy: 2.1.0 from /usr/lib/python2.7/site-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/site-packages
  requests>=2.0: 2.18.4 from /usr/lib/python2.7/site-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
    idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/site-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
  setuptools: 36.6.0 from /usr/lib/python2.7/site-packages
  tornado>=3.2: 4.5.2 from /usr/lib/python2.7/site-packages
    singledispatch: 3.4.0.3 from /usr/lib/python2.7/site-packages
      six: 1.11.0 from /usr/lib/python2.7/site-packages
    backports_abc>=0.4: 0.5 from /usr/lib/python2.7/site-packages
Mopidy-GMusic: 2.0.0 from /usr/lib/python2.7/site-packages
  setuptools: 36.6.0 from /usr/lib/python2.7/site-packages
  Mopidy>=1.0: 2.1.0 from /usr/lib/python2.7/site-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/site-packages
    requests>=2.0: 2.18.4 from /usr/lib/python2.7/site-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
      idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/site-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
    setuptools: 36.6.0 from /usr/lib/python2.7/site-packages
    tornado>=3.2: 4.5.2 from /usr/lib/python2.7/site-packages
      singledispatch: 3.4.0.3 from /usr/lib/python2.7/site-packages
        six: 1.11.0 from /usr/lib/python2.7/site-packages
      backports_abc>=0.4: 0.5 from /usr/lib/python2.7/site-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/site-packages
  gmusicapi>=10.1: 10.1.2 from /usr/lib/python2.7/site-packages
    validictory!=0.9.2,>=0.8.0: 1.1.1 from /usr/lib/python2.7/site-packages
    decorator>=3.3.1: 4.1.2 from /usr/lib/python2.7/site-packages
    mutagen>=1.34: 1.39 from /usr/lib/python2.7/site-packages
    requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0: 2.18.4 from /usr/lib/python2.7/site-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
      idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/site-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
    python-dateutil!=2.0,>=1.3: 2.6.1 from /usr/lib/python2.7/site-packages
      six>=1.5: 1.11.0 from /usr/lib/python2.7/site-packages
    proboscis>=1.2.5.1: 1.2.6.0 from /usr/lib/python2.7/site-packages
    protobuf>=3.0.0: 3.4.1 from /usr/lib/python2.7/site-packages
      six>=1.9: 1.11.0 from /usr/lib/python2.7/site-packages
      setuptools: 36.6.0 from /usr/lib/python2.7/site-packages
    oauth2client>=1.1: 4.1.2 from /usr/lib/python2.7/site-packages
      httplib2>=0.9.1: 0.10.3 from /usr/lib/python2.7/site-packages
      pyasn1>=0.1.7: 0.3.7 from /usr/lib/python2.7/site-packages
      pyasn1-modules>=0.0.5: 0.1.5 from /usr/lib/python2.7/site-packages
        pyasn1<0.4.0,>=0.3.4: 0.3.7 from /usr/lib/python2.7/site-packages
      rsa>=3.1.4: 3.4.2 from /usr/lib/python2.7/site-packages
        pyasn1>=0.1.3: 0.3.7 from /usr/lib/python2.7/site-packages
      six>=1.6.1: 1.11.0 from /usr/lib/python2.7/site-packages
    mock>=0.7.0: 2.0.0 from /usr/lib/python2.7/site-packages
      funcsigs>=1: 1.0.2 from /usr/lib/python2.7/site-packages
      pbr>=0.11: 3.1.1 from /usr/lib/python2.7/site-packages
      six>=1.9: 1.11.0 from /usr/lib/python2.7/site-packages
    appdirs>=1.1.0: 1.4.3 from /usr/lib/python2.7/site-packages
    gpsoauth>=0.2.0: 0.4.1 from /usr/lib/python2.7/site-packages
      pycryptodomex>=3.0: 3.4.7 from /usr/lib/python2.7/site-packages
      requests: 2.18.4 from /usr/lib/python2.7/site-packages
        chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
        idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/site-packages
        urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
    MechanicalSoup>=0.4.0: 0.9.0.post4 from /usr/lib/python2.7/site-packages
      requests>=2.0: 2.18.4 from /usr/lib/python2.7/site-packages
        chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
        idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/site-packages
        urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
      beautifulsoup4: 4.6.0 from /usr/lib/python2.7/site-packages
      six>=1.4: 1.11.0 from /usr/lib/python2.7/site-packages
      lxml: 4.1.1 from /usr/lib/python2.7/site-packages
    six>=1.9.0: 1.11.0 from /usr/lib/python2.7/site-packages
    future: 0.16.0 from /usr/lib/python2.7/site-packages
  requests>=2.0: 2.18.4 from /usr/lib/python2.7/site-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
    idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/site-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
  cachetools>=1.0: 2.0.1 from /usr/lib/python2.7/site-packages
GStreamer: 1.12.3.0 from /usr/lib/python2.7/site-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.26.1
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad

**Comment by Essir** [comment]
Hello? Can you do something about this please?(

**Comment by jjok** [comment]
Is this related to some of the other playback-related issues that are open at the moment?

```
ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))
2017-11-06 20:30:36,040 WARNING [25596:Core-10] mopidy.core.tracklist: Track is not playable: gmusic:track:Tc3ob2lia3bokvfytx2bqotb24e
```

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
