### ISSUE TITLE
Play top songs for an artist

### ISSUE THREAD

**Issue by cgpuglie** [mopidy/mopidy-gmusic#184]
Google's gmusic UI provides a list of top songs for an artist and allows you to play that list instead of just a specific album or song. Would it be possible/practical to implement a similar feature in mopidy-gmusic?

I was considering that it might be possible to return this list as an album, but not sure it really meets those qualifications. Any other ideas or suggestions?

I'd be willing to make a PR, but want to get some general feedback as to how or if this should be implemented.

Thanks!

**Comment by belak** [comment]
It's possible to put a bunch of unrelated songs in a folder (as an example, I think it's one way to view playlists... and it's how radio stations are handled).

As long as there's an API for it and there's support in the gmusicapi project, it'll be possible to add.

**Comment by cgpuglie** [comment]
Great, thanks for the advice. I'll explore this a little further and hopefully have a PR sometime this weekend.

**Comment by adnidor** [comment]
It seems that gmusicapi lacks support for this.

Upstream issue: simon-weber/gmusicapi#607

**Comment by adnidor** [comment]
Got it working in https://github.com/adnidor/mopidy-gmusic/tree/top-tracks

Still needs testing and refining, but if anyone wants to test it, go for it
