### ISSUE TITLE
Way to debug failed login to Google Music?

### ISSUE THREAD

**Issue by cmatzenbach** [mopidy/mopidy-gmusic#189]
So I've been using mopidy for quite some time, with the same settings and it's always worked fine.  However, when I tried to connect today it gave me the "Failed to login to Google Music as..." error.  I can login through my browser using the same username/password, everything is fine with my account.  I don't force a deviceid nor am I near my device limit.  Is there any way to figure out what changed/what is going wrong?

**Comment by belak** [comment]
Can you post the whole error (with relevant info redacted)?

**Comment by cmatzenbach** [comment]
Sure thing:

INFO     Starting Mopidy 2.1.0
INFO     Loading config from builtin defaults
INFO     Loading config from /home/matzy/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, stream, gmusic, softwaremixer, file
INFO     Disabled extensions: m3u, local
WARNING  Found local configuration errors, the extension has been automatically disabled:
WARNING    local/media_dir must be set.
WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, FileBackend, GMusicBackend
INFO     Audio output set to "autoaudiosink"
ERROR    Failed to login to Google Music as {redacted}
INFO     Start refreshing Google Music library
INFO     Start refreshing Google Music playlists
INFO     Starting Mopidy core
INFO     Finished refreshing Google Music library in 0s
INFO     Loaded 0 playlists from Google Music
INFO     Finished refreshing Google Music playlists in 0s
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend, GMusicScrobblerFrontend
INFO     MPD server running at [::]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     Starting GLib mainloop

Not too much there, other than the login failed.  Thanks for the help.

**Comment by belak** [comment]
Are you using two-factor login? If you are you'll need to set up an app password and use that here.

Otherwise, I'm not sure and this (unfortunately) doesn't have much to go on.

**Comment by lacymorrow** [comment]
I haven't been using two-factor (shame), but tried with `deviceid =`, `deviceid = mac`, and `deviceid = <random android id>`

**Comment by lacymorrow** [comment]
Upgraded to two-factor, still no luck.

**Comment by rjdang** [comment]
Mopidy enforces "deviceid" but the login method expects device_id, and it's not translated. MAC login method seems to no longer works with 2FA. Replacing the var name fixed it for me.

```bash
git clone https://github.com/mopidy/mopidy-gmusic/
cd mopidy-gmusic
sed -i 's/device_id/deviceid/g' ./mopidy_gmusic/session.py
pip install -U .
```

Related:
  - [https://github.com/simon-weber/gmusicapi/issues/620](https://github.com/simon-weber/gmusicapi/issues/620)
  - [https://github.com/simon-weber/gmusicapi/issues/626](https://github.com/simon-weber/gmusicapi/issues/626)

**Comment by belak** [comment]
Newer versions of gmusicapi have a completely different method of logging in (supported in the mopidy-gmusic master branch). This should fix most issues with authentication people have been having. If you get a chance to try it out, please let me know!
