### ISSUE TITLE
403 on track play

### ISSUE THREAD

**Issue by morgoth** [mopidy/mopidy-gmusic#192]
I started receiving 403 on track play - searching works fine.
I didn't change anything in my settings and didn't update any package. It just started throwing 403 yesterday.

Anyone experiencing similar issue.
Any advice how to debug it?

**Comment by adnidor** [comment]
I experienced the exactly same problem yesterday, it stopped after I put the ID of an android device instead of the default MAC-ID.

From that, I'd guess that google added an plausibility check for device ID to their API or otherwise changed the processing of IDs.

If that really is the cause, there's not much we can do about it, apart from mentioning it in the README

Do you use a manually configured device id or the automatically generated default?

**Comment by adnidor** [comment]
Did you put a Android or iOS id?

**Comment by morgoth** [comment]
android one - I used this app https://play.google.com/store/apps/details?id=com.evozi.deviceid

**Comment by adnidor** [comment]
After shortly testing the app I found that it displayed an incorrect deviceid.

Could you try running the latest master branch without a deviceid configured? It will show you all devices including ID that are registered on your account. Then use the deviceid from there in your mopidy.conf

**Comment by morgoth** [comment]
@adnidor Thank you so much. The log output helped. Indeed the device id is different. After changing it to the correct one it works. :-)

**Comment by kingosticks** [comment]
> By default, Mopidy-GMusic will use your system's MAC address 

Any ideas why this is no longer "plausible"? If it's required that people now enter the real mac address of their mobile phone then the readme should reflect that.

**Comment by adnidor** [comment]
#149 seems relevant here. If Google no longer allows MAC-IDs to be used, maybe implementation of this feature should be reconsidered

**Comment by kingosticks** [comment]
And possibly the same thing upstream: https://github.com/simon-weber/gmusicapi/issues/590

**Comment by fergyfresh** [comment]
I ran into the issue of not being able to use MAC-IDs that are constantly changing. If its a static MAC ID its fine, but if you send too many requests with different MAC IDs they end up blocking you. I ran into this here https://github.com/stevenleeg/geemusic/pull/214.

**Comment by PoLoMoTo** [comment]
I seem to be experiencing the same issue with MusicBox on a Raspberry Pi, the initial unset device-id results in the 403 when attempting to play however adding the android device ID from the app mentioned causes the Google Play Music folder to disappear entirely.  Any ideas what I'm missing?  I can post my debug log if necessary, is there any information contained in the log I should be concerned about posting?

**Comment by adnidor** [comment]
@PoLoMoTo Are there any errors in the log? A disappearing gmusic folder points to mopidy-gmusic not loading.
Can you post the relevant config?
