### ISSUE TITLE
Playlists don't show song infos

### ISSUE THREAD

**Issue by adnidor** [mopidy/mopidy-gmusic#194]
When saving gmusic tracks to a mopidy playlist and then playing back this playlist no info is displayed except the song title.

Not sure if this is a mopidy or mopidy-gmusic issue

Will look further into this if I have time

**Comment by jjok** [comment]
Does it work ok for other backends?
Which frontend are you using?

**Comment by adnidor** [comment]
Just checked, other backends don't work either. Seems to be a problem in mopidy

I'm using ncmpcpp

**Comment by adnidor** [comment]
Just had a look around in mopidys bugtracker, this seems to be a duplicate of mopidy/mopidy#1511
