### ISSUE TITLE
Google Music not playing

### ISSUE THREAD

**Issue by JJDrill** [mopidy/mopidy-gmusic#197]
Looks like this is a re-occurring issue, but I wanted to open a new ticket since I'm not sure it's related to what I've seen in previous issues.

I am able to authenticate to google music, but when I try and play a song I'm getting a HTTP 403 forbidden. I was using a app password at first, but tried turning off 2 factor auth and entered in my standard credentials. That unfortunately did not work either. Below is the error I'm seeing in the mopidy log. FYI - I have tried re-imaging Pi MusicBox and that can play all the default streams just fine.

One final note, it does say to check that my device id is set correctly, but I did confirm that ID is being set below. I just commented that ID out for this post.

2018-06-23 15:56:30,297 - WARNING  Failed to get stream url for T3tqaaw3dd5qnrxh3zvkahnhtoa.
2018-06-23 15:56:30,298 - WARNING  Please ensure your deviceid is set correctly.
2018-06-23 15:56:30,298 - ERROR    Call to Google Music failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 32, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 90, in get_stream_url
    return self.api.get_stream_url(song_id, quality=quality)
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 393, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=med&mjck=T3tqaaw3dd5qnrxh3zvkahnhtoa&pt=e&slt=1529765789972&tier=aa&sig=656pXV_UCX-Zt0el81BTfBmXC1g&hl=en_US&dv=0&net=mob
(requests kwargs: {u'url': u'https://mclients.googleapis.com/music/mplay', u'headers': {u'X-Device-ID': u'YES_THIS_WAS_MY_DEVICE_ID', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'med', u'mjck': u'T3tqaaw3dd5qnrxh3zvkahnhtoa', u'pt': u'e', u'slt': '1529765789972', u'tier': u'aa', u'sig': '656pXV_UCX-Zt0el81BTfBmXC1g', u'hl': u'en_US', u'dv': 0, u'net': u'mob'}, u'method': u'GET'})
(response was: u'<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
2018-06-23 15:56:30,300 - WARNING  Track is not playable: gmusic:track:T3tqaaw3dd5qnrxh3zvkahnhtoa

**Comment by kingosticks** [comment]
So at first glance it sounds like this is related to the recent issue (maybe now closed but I thought we changed the readme) where you have to now use a same deviceid as one your devices I.e. your phone.

**Comment by JJDrill** [comment]
Ok, interesting. I just fixed it and here's what I did. I tried setting the device ID to the one my MacBook uses and the one my phone uses, but received the following error:

`
InvalidDeviceId: Invalid device_id xxxxxxxxxxxxxxxx. Your valid device IDs are:
* xxxxxxxxxxxxxxxx (16 digits)
* xxxxxxxxxxxx (12 digits)
* xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (64 bits, but truncated to 40)
* xxxxxxxxxxxx (12 digits)
2018-06-23 18:17:28,213 - ERROR    Actor died: GMusicBackend (urn:uuid:3bcb20d5-d700-41e9-8107-c65b314afefe) stopped before handling the message
`

I tried to then enter in the first ID listed above (which by the way was NOT the device ID for the active network adapter being used on my Raspberry Pi), and it started to work. I then tried the remaining 3 Pi device ID's.  Here are the results for all:

1. This one worked.
2. This is my active nic, but did not work.
3. This 64 digit was truncated to 40, and did not work.
4. This one did not work.

So, it looks like the very first one is the only one which works. I'm up and running now, but I hope this helps a little to try and figure out what the root cause is.

**Comment by bdn76** [comment]
Confirm:

`ERROR    Call to Google Music failed
Traceback (most recent call last):
  File "/home/dima/.local/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 32, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/dima/.local/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 90, in get_stream_url
    return self.api.get_stream_url(song_id, quality=quality)
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/home/dima/.local/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/home/dima/.local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 393, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/home/dima/.local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/dima/.local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=med&mjck=T4tfgxaux6phuxra43hbaz776m4&pt=e&slt=1530085701462&tier=aa&sig=9Dlcjhgr0_6GBJ8PHMFpOTMmBG8&hl=en_US&dv=0&net=mob
(requests kwargs: {u'url': u'https://mclients.googleapis.com/music/mplay', u'headers': {u'X-Device-ID': u'8081BCAD30C9', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'med', u'mjck': u'T4tfgxaux8phuxra43hbaz776m4', u'pt': u'e', u'slt': '1530085701462', u'tier': u'aa', u'sig': '9Dlcjhgr0_6GBJ8PHMFrOTMmBG8', u'hl': u'en_US', u'dv': 0, u'net': u'mob'}, u'method': u'GET'})
(response was: u'<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
`

**Comment by kingosticks** [comment]
Did you set your device ID to something valid as per the readme?

**Comment by bdn76** [comment]
Of course and get correct playlists from Google but item of playlist not play:

`
...
INFO     Logged in to Google Music
INFO     Start refreshing Google Music library
INFO     Start refreshing Google Music playlists
...
INFO     Starting GLib mainloop
INFO     Finished refreshing Google Music library in 93s
...
`

**Comment by kingosticks** [comment]
So what exactly are you using? The device ID of your phone? I'm not sure the deviceid is used except for playback. We need more information considering the original issue was resolved (but for some reason not closed).

**Comment by bdn76** [comment]
Hmm... I don't understand you. Here's mopidy config:

[gmusic]
username = xxx
password = yyy

And it work's fine for interaction with Google:

INFO     Starting Mopidy 2.1.0
...
INFO     Logged in to Google Music
INFO     Start refreshing Google Music library
INFO     Start refreshing Google Music playlists
...
INFO     Loaded 1 playlists from Google Music
INFO     Finished refreshing Google Music playlists in 108s
INFO     Finished refreshing Google Music library in 132s


i'mm see my song's and playlists but selected song from playlist not playing (error shown before).

**Comment by kingosticks** [comment]
I'll try again. What device ID are you using? Where did you get it from?

If you are going to post configs and logs post the full config and the full log. What you think is relevant may not be correct.

**Comment by bdn76** [comment]
Full config (without name and password):

$ cat .config/mopidy/mopidy.conf | grep -v ^#

[core]

[logging]

[audio]
output = pulsesink server=/var/run/pulse/native device=alsa_output.usb-E-MU_Systems__Inc._E-MU_0204___USB_E-MU-FC-3F19-07DA0C0E-0D8B0-8740AT2A-00.analog-stereo

[proxy]

[mpd]
hostname = 0.0.0.0

[http]
hostname = 0.0.0.0

[stream]

[m3u]

[softwaremixer]

[file]

[local]
media_dir = /mnt/cloud/public/music

[tunein]

[local-sqlite]

[local-images]

[iris]
country = RU
locale = ru_RU

[gmusic]
username = xxx
password = yyy

Full log with error:

WARNING  Failed to get stream url for T4tfgxaux6phuxra43hbaz776m4.
WARNING  Please ensure your deviceid is set correctly.
ERROR    Call to Google Music failed
Traceback (most recent call last):
  File "/home/dima/.local/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 32, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/dima/.local/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 90, in get_stream_url
    return self.api.get_stream_url(song_id, quality=quality)
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/home/dima/.local/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/home/dima/.local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 393, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/home/dima/.local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/dima/.local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=med&mjck=T4tfgxaux6phuxra43hbaz776m4&pt=e&slt=1530090501150&tier=aa&sig=9MJbVk6khgd-pKJx011oXS7beKU&hl=en_US&dv=0&net=mob
(requests kwargs: {u'url': u'https://mclients.googleapis.com/music/mplay', u'headers': {u'X-Device-ID': u'7071BCAD30C9', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'med', u'mjck': u'T4tfgxaux6phuxra43hbaz776m4', u'pt': u'e', u'slt': '1530090501150', u'tier': u'aa', u'sig': '9MJbVk6khgd-pKJx011oXS7beKU', u'hl': u'en_US', u'dv': 0, u'net': u'mob'}, u'method': u'GET'})
(response was: u'<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
WARNING  Track is not playable: gmusic:track:T4tfgxaux6phuxra43hbaz776m4

I do not know about device id you mean - i'm see it in log but not found in config.

**Comment by kingosticks** [comment]
Now I'm confused. In my first reply to you I asked had you set the device ID as per the readme  and you replied "of course". 

Please read the entire  configuration section of the readme file in this repository.

**Comment by kingosticks** [comment]
Thanks @adnidor. 
```
pip install https://github.com/mopidy/mopidy-gmusic/archive/master.zip
```

**Comment by kingosticks** [comment]
@adnidor, could you cut a release? I'm surprised this isn't coming up more often. I think we can make it a little clearer in the readme by moving that section above all that other optional stuff (still obviously assumes you read it).

**Comment by bdn76** [comment]
Works now after specifing device id. Thanks!

**Comment by belak** [comment]
This slipped through the cracks. I meant to get a release together a few weeks back. I'll try turning get this done today.

**Comment by belak** [comment]
I just pushed 3.0.0 to PyPI so this should at least warn you on startup when misconfigured. Thanks for the report!

**Comment by Deep-Six** [comment]
I am having the same problem, I never had  to set deviceid before and it worked... I tried an app called device id and it showed a few different things:
Android Device ID that was 16 Alpha-numeric chars that didn't work 
and something called Google Service Framework (GSF)
also 16 alphanumeric chars that DID work for deviceid
Hope this helps someone..

**Comment by belak** [comment]
The latest published version will print your device IDs in the log if you start up without one in the settings.
