### ISSUE TITLE
artist not found

### ISSUE THREAD

**Issue by pietrondo** [mopidy/mopidy-gmusic#202]
Hi
I installed mopidy on last stretch lite raspbian and gmusic works.. except when i search for the artist:
Artist not found..
SO i can't find all music from specific artist but only specific music

why?

**Comment by jjok** [comment]
Which frontend are you using?

**Comment by mbrownnycnyc** [comment]
I have the problem in both Mopidy-MusicBox-Webclient and Mopidy-Mobile persistently.

**Comment by brandonfyia** [comment]
I have this problem as well.

**Comment by it-unit-iiep** [comment]
For me, via PI Musicbox, I can search for artists but when I click on the search result, I end up getting Artist not found.  However, clicking on an Album from the results would display the album correctly.  Any ideas ?

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
