### ISSUE TITLE
Cannot find a device id to use

### ISSUE THREAD

**Issue by Dropbear67** [mopidy/mopidy-gmusic#204]
I cannot find a device id to use after setting up 2 factor authentication. What is the method for someone who does not have an android phone to find a valid device id that I can use in piMusicBox implementation of mopidy

**Comment by jjok** [comment]
The README says:

> You can either use one of those IDs in your config file, or use the special value `mac` if you want gmusicapi to use the old method of generating an ID from your MAC address.

Have you tried that?

**Comment by Dropbear67** [comment]
The issue is that I cannot find any device id to use. the README file says that a list of device id's will be displayed but i cannot find this list in the log.

I have not tried "mac" but I do not believe that works anymore?

**Comment by djl236** [comment]
Not working for me either. I have the correct DeviceID of my android phone in the config and even got the Google alert that I signed in but Google Music doesn’t load at all.

I get the following error in the console when checking the status of mopidy:

Nov 03 11:51:41 mopidy mopidy[1670]: ERROR Actor died: GMusicBackend (urn:uuid:7b26d467-e1a0-4fd7-a297-2196b93a7434) not found

Now that UUID is not of my current phone but my old one. Perhaps I need to update that but I don’t see where. The config only has device id.

**Comment by chupy35** [comment]
I have the same problem,

**Comment by nkoporec** [comment]
Having the same issue.

**Comment by djl236** [comment]
Which issue are you both having, mine or the OPs?

**Comment by nkoporec** [comment]
I'm having an issue where my device id and username and password is correct but Google Music won't work, it fails because of the wrong device id(double checked and I'm using the correct device id from my android phone).

**Comment by chupy35** [comment]
> Which issue are you both having, mine or the OPs?

I think is the same issue or not?

**Comment by djl236** [comment]
No I'm having this actor died error. I created a new issue for it. I'm just waiting for a reply.

**Comment by SimLoads** [comment]
I'm having this issue too, MAC doesn't work nor does substituting 'mac' for an _actual_ MAC address do anything

**Comment by mbrownnycnyc** [comment]
dropbear87 had stated that they can't find the entry in the log file.  But I had no problem.  When I didn't provide a `deviceid` in the config, and mopidy-gmusic queried and output a list of device IDs.  You must provide a proper `username` and `password` ( of course), and I think you must have initiated a device before.

**Comment by mbrownnycnyc** [comment]
Hey guys,

The log file locations are covered in:
    /etc/mopidy/mopidy.conf --> /var/log/mopidy/mopidy.log
    or `stdout`
    or `journalctl -u mopidy`

I use mopidy within docker with the hass.io add-on "framework," so this purposefully dumps to stdout and is logged through the hass.io add-in mechanism (I think).  Therefore, I see the log entries within the hass.io web UI.

mopidy-gmusic uses "gmusicapi", a python interface to google music (https://github.com/simon-weber/gmusicapi), so some questions may cross over to the original code base, or you may find more assistance there.

**Comment by belak** [comment]
Newer versions of gmusicapi should output devices attached to the account when an invalid one is used. If you're still having issues with this, please feel free to file another issue.
