### ISSUE TITLE
device id without android phone ?

### ISSUE THREAD

**Issue by giann** [mopidy/mopidy-gmusic#205]
I generated an App Password but I still can't login. No device id is listed just a "Failed to login" error.
How do I get a device id without an android phone ?

**Comment by adnidor** [comment]
You can try the mac device id, but that probably won't work. Still worth a shot though.

Then you could try to invent a device id that looks similar to the android device ids and see if google accepts that.

If that still doesn't work, try running gmusic in an android emulator, signing in, and using the id of the emulator in gmusic

**Comment by mbrownnycnyc** [comment]
mopidy-gmusic uses gmusicapi (a python project) as a backend to interface with google music.  Therefore, you can look to related issues: https://github.com/simon-weber/gmusicapi/issues/149

> Try removing the prefix '0x' from the id.

Might be a solution.

**Comment by belak** [comment]
Newer versions of gmusicapi should output devices attached to the account when an invalid one is used. If you're still having issues with this, please feel free to file another issue.
