### ISSUE TITLE
Failed building wheel for lxml

### ISSUE THREAD

**Issue by dony71** [mopidy/mopidy-gmusic#208]
get this error while installing "pip install mopidy-gmusic"
...............
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-EEvVvy/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-armv7l-2.7/src/lxml/etree.o -w
  arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-EEvVvy/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-EEvVvy/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/src/lxml/etree.o -lxslt -lexslt -lxml2 -lrt -lz -lm -o build/lib.linux-armv7l-2.7/lxml/etree.so
  /usr/bin/ld: cannot find -lz
  collect2: error: ld returned 1 exit status
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
..................

any idea?

**Comment by garrettn** [comment]
I'm running into the same problem. There is no `libxml-dev` package. I did install `libxml2-dev` and `libxslt1-dev`, but the `mopidy-gmusic` installation is still failing at the `lxml` step.

**Comment by mbrownnycnyc** [comment]
try: `apt-get install python-lxml`

**Comment by guythnick** [comment]
I was able to get this to compile by installing these packages:
`sudo apt-get install libxml2-dev libxslt1-dev`

**Comment by garrettn** [comment]
I will try that when I get a chance. Thanks, everyone!

**Comment by garrettn** [comment]
That seemed to work for me. mopidy-gmusic installed after @guythnick's suggestion. Thank you!

**Comment by belak** [comment]
Glad you got this resolved!
