### ISSUE TITLE
Refreshing tracks from library

### ISSUE THREAD

**Issue by foobarth** [mopidy/mopidy-gmusic#21]
Hi,

if i read the code correctly, track database is only refreshed after a successful login at startup, but never again - until mopidy gets restarted. Is there any way to force such a refresh? Problem is if you add tracks from All Access via the Web Player, they never show up in Mopidy until you restart the daemon. As i tend to leave the box on for days without a reboot (Raspberry Pi), this kinda sucks :)

**Comment by wilberking** [comment]
I'd like to understand what this is suppose to do:

Refresh library

curl -X POST -H Content-Type:application/json -d '{ "method": "core.library.refresh", "jsonrpc": "2.0", "params": { "uri": null }, "id": 1 }' http://localhost:6680/mopidy/rpc

Will this force all my albums, artists, song to be loaded?  That's what seems to be taking a long time to occur right now with my Gmusic library.  It seems that Playlists are there and persist;  but selecting artists and albums take a while and are not cached.

**Comment by ScottG489** [comment]
If you add a song to your Google Play Music library, it won't be reflected in mopidy. Calling that will update it reflect the current state of your online library. It's possible that it does indeed need to be run every time and is not cached. However, I don't interact with my library very much and do so instead with my playlists so I might not have noticed. I never noticed any sort of caching though. Every time I started mopidy with this plugin enabled it seemed to take the same amount of time to start and when I was debugging it looked like it was pulling everything down in my playlists each time.

**Comment by jodal** [comment]
Regular background refreshing was implemented by @felixb in commits 9406ef77d8d84040b2377cebbc209099e13503bd and 008c8b136e3e536b28741e770ed4aa8602191e4c over a year ago. It'll be part of the upcoming 1.0.0 release.
