### ISSUE TITLE
Possible to integrate radio station creation?

### ISSUE THREAD

**Issue by mbrownnycnyc** [mopidy/mopidy-gmusic#211]
I;d like to request a feature to create a radio station.  I'm not sure how to use the interface for such a thing.  The interface is available in the gmusicapi ( https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html?highlight=radio#radio-stations )

Thanks.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
