### ISSUE TITLE
listening to subscribed playlists

### ISSUE THREAD

**Issue by ofwinterpassed** [mopidy/mopidy-gmusic#213]
I would love to get access to my subscribed playlists i.e. other peoples playlists that I subscribe to.

**Comment by belak** [comment]
This should work out of the box. All playlists are grabbed and should be displayed properly (even ones you subscribe to). Note that playlist refreshing takes a bit longer than library refreshing, so if you're having issues with that (and/or need help debugging) please feel free to file a new issue with more information. Thanks!
