### ISSUE TITLE
Library management

### ISSUE THREAD

**Issue by w1d3m0d3** [mopidy/mopidy-gmusic#214]
How can songs be added and removed from the google music library? That is, add a song or album from all access to my library or remove a song. I've not found any way to do that and I am not sure is it possible since there is no documentation on that topic.

If there is no way to do this as of right now may I suggest having a playlist called `Google Play Music Library` in which songs/albums can be added and removed and have it propagate to the library stored by Google. Of course, that would mean this playlist can only hold gmusic songs but that's okay.

EDIT: perhaps there should also be playlists exported for thumbs up/down, or some other (and saner) interface for those

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
