### ISSUE TITLE
Album artist id's are wrong

### ISSUE THREAD

**Issue by sebsebmc** [mopidy/mopidy-gmusic#215]
When searching, albums will return their artists as the md5 of the artist name, not the artist ID that is returned from gmusicapi. https://github.com/mopidy/mopidy-gmusic/blob/bbfe876d2a7e4f0f4f9308193bb988936bdfd5c3/mopidy_gmusic/library.py#L626

I have a fix in my commit sebsebmc/mopidy-gmusic@2a081de654e7f1fa90ac5e840df3e75dc0815d05, but I don't know why the artist ID wasn't used in the first place.

I haven't cleaned up the code yet but if this is the right fix I can clean up the code and submit a pull request.

**Comment by jjok** [comment]
I think this should no longer be an issue since #233 has been merged, although I haven't specifically heard from anyone with a subscription who has tried those changes.

**Comment by sebsebmc** [comment]
This actually creates the issue that the new id's don't match what the gmusic API uses and means that if you try and library browse a gmusic:artist:artist_id using the returned id it will not work.

Basically if I search and get an artist id I cannot use that artist id to browse that artist anymore if I were to use your fix.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
