### ISSUE TITLE
Mopidy-GMusic version 4.0.0 not published on https://pypi.org

### ISSUE THREAD

**Issue by DamienGarrido** [mopidy/mopidy-gmusic#216]
Hello,

Version 4.0.0 of Mopidy-GMusic has not been released yet on [PyPI](https://pypi.org/project/Mopidy-GMusic/), thus 
I'm unable to install it through pip.

The last published version (3.0.0) seems to not work anymore (unable to log in), using the username / password / deviceid credentials.

Cloning the 4.0.0 version under site-packages works as a workaround.

**Comment by belak** [comment]
Yes, there wasn't much response in the thread relating to the login issue and I don't want to release something publicly that breaks backwards compatibility without feedback. I haven't had the time to test this much myself either.

I list upcoming releases in the readme with features that are in master but not published under an "In Progress" heading so I don't need to make a changelog when the full release comes around.

**Comment by susnux** [comment]
The login works fine with 4.0.0 (< 4 is broken).
But https://github.com/mopidy/mopidy-gmusic/issues/224 is broken in 4.0.0

**Comment by belak** [comment]
Once that's fixed, a 4.0 release would definitely be warranted.

**Comment by bahuma20** [comment]
For a temporary workaround, you can install it via git...

For this first uninstall the package:
`pip uninstall mopidy-gmusic`

Then install from git:
`pip install git+git://github.com/mopidy/mopidy-gmusic.git`

**Comment by jodal** [comment]
Mopidy-GMusic 4.0.0 is now on PyPI.

Please note that it depends on Mopidy 3.0.0, which requires Python >= 3.7.
