### ISSUE TITLE
No URL output when starting mopidy

### ISSUE THREAD

**Issue by MichaelMallett** [mopidy/mopidy-gmusic#219]
The documentation states that I will be given a url when starting mopidy, unfortunately this doesn't happen. Tried looking through the config and all I get is that gmusic is disabled due to config check, and this in the logs

`mopidy.ext: Disabled extension gmusic: (pyasn1 0.1.9 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.1'), set(['pyasn1-modules']))`

How can I force this url generation?

**Comment by MichaelMallett** [comment]
This is the full output when I start mopidy outside of the service

`
INFO     Starting Mopidy 2.2.2
INFO     Loading config from builtin defaults
INFO     Loading config from /etc/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Disabled extension gmusic: (pyasn1 0.1.9 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.1'), set(['pyasn1-modules']))
INFO     Enabled extensions: spotify, mpd, http, stream, m3u, softwaremixer, file, local
INFO     Disabled extensions: gmusic
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend, SpotifyBackend
INFO     No local library metadata cache found at /var/lib/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Logged in to Spotify in offline mode
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
INFO     HTTP server running at [::ffff:0.0.0.0]:6680
INFO     Starting GLib mainloop
INFO     Logged in to Spotify in online mode`

**Comment by kingosticks** [comment]
Doesn't that log say gmusic is disabled due to what looks like a dependency problem with pyasn1?

**Comment by MichaelMallett** [comment]
Does it? I'm not sure tbh I'm not that familiar with python and as pip installed it I assumed dependencies were met. I'll try installing that.

**Comment by kingosticks** [comment]
Pip should have taken care of this. However, note that if you installed with `pip install <blah>` it'll install everything in a place that only your logged in user can access. If you want to use the service, that runs as a different user, and so make sure you use `sudo pip install <blah>.

**Comment by MichaelMallett** [comment]
Yeah I've been having to use sudo to install everything since having to change pip version too, so it's picking things up. Not sure why it didn't handle the dependency, but oh well. Anyway, that worked but now I get a different error when it tries to give me a device list

```
ERROR    Failed to login to Google Music as "mike@generalpie.com"
ERROR    There is no gmusic deviceid set. Registered devices are listed below.
ERROR    Unhandled exception in GMusicBackend (urn:uuid:121d07f6-8675-491e-8ac4-efb00e91ac23):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/backend.py", line 57, in on_start
    for device in self.session.api.get_registered_devices():
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 879, in get_registered_devices
    res = self._make_call(mobileclient.GetDeviceManagementInfo)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 48, in _make_call
    return super(Mobileclient, self)._make_call(protocol, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 90, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 213, in perform
    response = session.send(req_kwargs, required_auth)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 113, in send
    raise NotLoggedIn
NotLoggedIn
ERROR    Actor died: GMusicBackend (urn:uuid:121d07f6-8675-491e-8ac4-efb00e91ac23) stopped before handling the message
```

**Comment by MichaelMallett** [comment]
I'll close this and raise a seperate issue

**Comment by kingosticks** [comment]
That uuid is an internal Mopidy identifier for something else. I would check your versions, [line 57 of the latest version](https://github.com/mopidy/mopidy-gmusic/blob/master/mopidy_gmusic/backend.py#L57) doesn't match your error message. In your new issue please provide outputs of `sudo mopidyctl deps` and `sudo mopidyctl config`.

**Comment by MichaelMallett** [comment]
@kingosticks I have created a new ticket, but the version I have of mopidy-gmusic is the latest version according to the outputs
