### ISSUE TITLE
Don't get a refresh token after putting the initial_code to the config file

### ISSUE THREAD

**Issue by david8sen4** [mopidy/mopidy-gmusic#223]
Hi,

I tried a lot to get this working but now im stuck at the part where I should get a refresh token after putting the initial_code I got from Google to the config file. 

Console output still lists the error with the link to get the initial code. I tried several times, killing the application, doing reboots, manually starting the application.....

 Maybe somebody would be so nice to explain the workflow how to get the refresh token more clearly so a noob like me will be able to understand. Your help would be highly appreciated. 

many thanks!

**Comment by david8sen4** [comment]
So I got this almost working right now.
My main fault has been using the wrong settings file.

I first used the settings for running as a service placed here: /etc/mopidy/mopidy.conf 
After that I tried to run mopidy by simply typing "mopidy" to the console.

After I placed my setting at the config file placed here "/home/pi/.config/mopidy/mopidy.conf" I got a refresh token.

My second problem is, that I have to run it as a service and to get gmusic working I had to install the extension a second time for the user "mopidy" using this command: 

sudo -u mopidy pip install https://github.com/mopidy/mopidy-gmusic/archive/master.zip

Had some issues with lxml and crashing OS all the time and had to try installation very often to get it installed. I tried five different SD Cards and multiple versions of Raspbian.

I still don't know where I can see the startup log for mopidy running as a service so I placed the same settings (refresh token) I got from running mopidy as user "pi" to the settings for running it as a service. 

I can search for songs from Gmusic in Iris right now but have not been able to play one of the songs. There is also an issue of mopidy disconnecting from Iris all the time. 

Maybe somebody can explain where I can see the URL for the gmusic extension refresh token while running mopidy as a service so I will try to do a fresh install hoping this will be the last.

many thanks!

**Comment by jjok** [comment]
From the docs:
> You can use journalctl to view Mopidy’s log, including important error messages:

```
sudo journalctl -u mopidy
```

> journalctl has many useful options, including -f/--follow and -e/--pager-end, so please check out journalctl --help and man journalctl.

https://docs.mopidy.com/en/latest/running/service/#service-management-with-systemd

**Comment by jodal** [comment]
Because of age and nothing concrete to address here, I'm closing this. Feel free to use the forum at https://discourse.mopidy.com to get further help.
