### ISSUE TITLE
Artist not found (every 'all-access' artists)

### ISSUE THREAD

**Issue by susnux** [mopidy/mopidy-gmusic#224]
There is a issue with the artists information with all-access music.
It works correct for my music uploaded to gmusic, but not for all access music.

So you can search for artists, but you can not get any info.
Error log I get: `Failed to lookup u'gmusic:artist:Aqq7xecoatyvzlh7ikx6u7d6s44'`
(from _lookup_artist in library.py)

**Comment by jodal** [comment]
Is this still an issue on Mopidy-GMusic 4.0.0 which was just released to PyPI?

**Comment by susnux** [comment]
Yes same issue still persists, sometimes the same happens for albums:
`Failed to lookup 'gmusic:album:pjhvssusdn7m5qbyaeaknptmke'`

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
