### ISSUE TITLE
Successful login, but no results found when search.

### ISSUE THREAD

**Issue by Deep-Six** [mopidy/mopidy-gmusic#229]
Hi, I am receiving this error, when I attempt to search my gmusic library, no results are shown in ncmpcpp as a result.

ERROR    2020-01-22 13:47:24,594 [1011082:Core-9] mopidy.core.library
  GMusicBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/lib/python3.8/site-packages/mopidy/core/library.py", line 316, in search
    result = future.get()
  File "/usr/lib/python3.8/site-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3.8/site-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3.8/site-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3.8/site-packages/mopidy_gmusic/library.py", line 388, in search
    lib_tracks, lib_artists, lib_albums = self._search_library(query, uris)
  File "/usr/lib/python3.8/site-packages/mopidy_gmusic/library.py", line 451, in _search_library
    self._validate_query(query)
  File "/usr/lib/python3.8/site-packages/mopidy_gmusic/library.py", line 526, in _validate_query
    for (_, values) in query.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by kingosticks** [comment]
Thanks, this changed in Python 3 and we missed it during the port.

**Comment by kingosticks** [comment]
Running 2to3 on the codebase shows a lot of redherrings but we should look closer since the tests are not doing much.

**Comment by NickHu** [comment]
I think I'm getting a similar error - I've just set up mopidy-gmusic, to use with mopidy-mpd and ncmpcpp. I don't have All Access, but I can play tracks I've uploaded only through `Browse: Google Play Music/Tracks`; if I look in `Browse: Google Play Music/Albums` or `Browse: Google Play Music/Artists`, I can see my albums and artists, however trying to access any of those 'folders' yields no tracks.

**Comment by kingosticks** [comment]
Please check your log for an error traceback similar to the above. https://docs.mopidy.com/en/latest/troubleshooting/ for more help with that.

**Comment by kingosticks** [comment]
@Deep-Six I am confused, what version of Mopidy-gmusic are you running here? Your line numbers do not match the source in this repo, `iteritems` [isn't used](https://github.com/mopidy/mopidy-gmusic/blob/master/mopidy_gmusic/library.py#L558) in the latest version. Can you make sure you are running version v4.0.0 and can we see your `mopidy deps` please.

**Comment by NickHu** [comment]
> Please check your log for an error traceback similar to the above. https://docs.mopidy.com/en/latest/troubleshooting/ for more help with that.

I get no errors or anything notable in the logs with `-vvvv`:

```
DEBUG    2020-01-24 09:11:07,673 [24604:MpdSession-18] mopidy_mpd.session
  Request from [::ffff:127.0.0.1]:38138: noidle
DEBUG    2020-01-24 09:11:07,673 [24604:MpdSession-18] mopidy_mpd.session
  Response to [::ffff:127.0.0.1]:38138: OK
DEBUG    2020-01-24 09:11:07,673 [24604:MpdSession-18] mopidy_mpd.session
  Request from [::ffff:127.0.0.1]:38138: lsinfo "Google Play Music/Albums/Radiohead - The Bends"
DEBUG    2020-01-24 09:11:07,674 [24604:GMusicBackend-6] mopidy_gmusic.library
  browse: gmusic:album:B4leblu5yxxyu33q4ij2zs65wuq
DEBUG    2020-01-24 09:11:07,709 [24604:MpdSession-18] mopidy_mpd.session
  Response to [::ffff:127.0.0.1]:38138: OK
DEBUG    2020-01-24 09:11:07,710 [24604:MpdSession-18] mopidy_mpd.session
  Request from [::ffff:127.0.0.1]:38138: idle
```

**Comment by kingosticks** [comment]
@NickHu Then your issue is not the same issue that was reported in this bug report. I don't have a Mopidy-Gmusic account but from what I can see, IDs starting with a 'B' signify an all access item and your log shows "gmusic:album:B4leblu5yxxyu33q4ij2zs65wuq". There is a fallback in this case to then find the album tracks in the user library, but the code comment suggests that should only occur for purchased tracks. If you think your album should be displayed then please open a new issue, or post on the user forums.

Im going to close this as I don't believe the original reported issue is present in the latest version. Feel free to re-open if that's not the case, and also include your `mopidy deps` output.

**Comment by kingosticks** [comment]
Oh, and the forms are at https://discourse.mopidy.com/

**Comment by Deep-Six** [comment]
hey @kingosticks  I am running an arch platform, 
aur/mopidy-gmusic 3.0.0-2 (+6 0.00%) (Out-of-date 2019-12-23) (Installed)
Mopidy extension for playing music from Google Play Music

**Comment by kingosticks** [comment]
The only Python 3 compatible release is the latest one (v4.0.0). The one on AUR needs updating.
