### ISSUE TITLE
All Access results returned from search when All Access not enabled

### ISSUE THREAD

**Issue by jjok** [mopidy/mopidy-gmusic#230]
Hi. I don't have All Access, but if I search for an album that I haven't uploaded, I get a load of results from All Access songs. That doesn't seem right.

A few of the methods in `library.py` have `if is_all_access` in them, but it doesn't look like any of the search-related code does.

**Comment by jjok** [comment]
Is this actually something that should be handled in this extension, or should it be that Google knows if I'm subscribed or not and decides what search results it should send back for me?

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
