### ISSUE TITLE
refresh_token not recognised

### ISSUE THREAD

**Issue by RossWilliamson** [mopidy/mopidy-gmusic#235]
After following the instructions and obtaining a refresh_token (I get instructed to add the token to the config file which I did, when running mopidy I still get

ERROR    2020-03-17 06:22:37,729 [219:GMusicBackend-4] mopidy_gmusic.session
  No refresh_token in gmusic config. Please run `mopidy gmusic login`.

I've tried with and without a device_id.  I checked to see if there was a device registered on google music and there was not.

I'm using the latest from git.

**Comment by jjok** [comment]
It sounds like your config file isn't quite right. Could you share what the `[gmusic]` section looks like (with passwords and tokens removed)?

**Comment by RossWilliamson** [comment]
See below

[gmusic]
refresh_token = long_token_starting_with_1//
deviceid = mac
enabled = false
username = none
password = none
all_access = true
bitrate = 320

**Comment by jjok** [comment]
You need to set your `username` and `password` as well as the `refresh_token` and `deviceid`.

I'm assuming you haven't explicitly set `enabled` to `false`, but if you have, that will disable the extension.

**Comment by RossWilliamson** [comment]
Sorry but I did actually set the uname and password and the enable is True (It's a node.js in a docker that updates the value) - The above is misleading (edited and updated).  for the device_id, my understanding is that I need to retrieve that from Google Music but when I go to google music there is no device registered.

**Comment by jjok** [comment]
Are you running the `mopidy` command or running as a service? Is the above config copied from your config file, or from the output of `mopidy config` / `mopidyctl config`?

**Comment by RossWilliamson** [comment]
running as command, however mopidy config did show that the refresh_token is emtpy!  I think it's something to do with how my docker and node.js is setup in terms of updating the config file.... (New at this).  I'll dig around but I think for the moment it's user error.....

**Comment by bi0shacker001** [comment]
I'm having the same issue with a standard install on archlinux, running mopidy with a systemd service as user mopidy.

**Comment by jjok** [comment]
It's the same solution then. If you run `mopidyctl config` and the config you entered isn't there, it means you're editing the wrong config file.

**Comment by bi0shacker001** [comment]
There is no wrong config file. I only have one file, /etc/mopidy/mopidy.conf
Everything is configured in there.

**Comment by bi0shacker001** [comment]
If there is somewhere else besides the system mopidy cinfig file that config information goes in, please feel free to share. I did my research before replying to this, and was unable to find anything.

**Comment by jjok** [comment]
Sounds like a different issue then. Try asking on the forum https://discourse.mopidy.com/.

**Comment by kingosticks** [comment]
Can you clarify that the refresh_token value you entered in /etc/mopidy/mopidy.cfg is present in the output of `sudo mopidyctl config`.

**Comment by bi0shacker001** [comment]
It isn't. Mopidyctl shows ******** as the value for refresh_token, which I assume is deliberate censoring

**Comment by kingosticks** [comment]
OK, right, but there is something there. Can you provide the entire startup log, up to the point you get the error message.

**Comment by bi0shacker001** [comment]
I just checked my logs, and they show google music as logged in, so I guess the issue must have resolved itself somewhere in the middle of the reinstalls and recreating the config file over and over again.

Sorry about that!

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
