### ISSUE TITLE
Google Play Music replaced by YouTube Music

### ISSUE THREAD

**Issue by Hoerli1337** [mopidy/mopidy-gmusic#240]
Will the plugin be adapted for YouTube Music?
Google Play Music will be switched off soon.

**Comment by natumbri** [comment]
The mopidy-youtube plugin has limited, experimental support for YouTube Music: https://github.com/natumbri/mopidy-youtube/issues/151#issuecomment-655877767.   Can't log in or access your account, but can search and play, to some extent.  YouTube API key not required, although some things work better if you have one.

**Comment by jodal** [comment]
@belak Are you okay with me going ahead marking this extension as deprecated and archiving the repo?

**Comment by belak** [comment]
Yeah, go for it. Might be good to add a commit with some background information if you've got the time, potentially with info about a YT Music plugin.

**Comment by jodal** [comment]
- [x] Remove Mopidy-GMusic (and python-gmusicapi) from Debian/Ubuntu
- [x] Remove Mopidy-GMusic (and python-gmusicapi) from apt.mopidy.com
- [x] Add warning to README (commit 5fe0bd1d9b0e3d5545d69bc05b62ff548d350757)
- [x] [Release v4.0.1](https://pypi.org/project/Mopidy-GMusic/) to PyPI, so the warning is on top there as well
- [x] Archive repository, right after closing this issue
