### ISSUE TITLE
Musicbox 0.4.3 and GMusic 

### ISSUE THREAD

**Issue by klucon2** [mopidy/mopidy-gmusic#25]
Hey everyone,
I basically have the same problem as described in this post:

https://groups.google.com/forum/?fromgroups=#!searchin/mopidy/google$20music/mopidy/YOB7noVdenI/SujH9Ys2v0YJ

The thing is I don't use the two-step-verification and it still doesn't work.

All I did was install pi musicbox, put in my google credentials (email, password and google service framework id (without the first two letters, so 14 digits in total)), but nothing happens. Also tried with the full 16 digits, still nothing.
I did notice that the volume level in the web interface drops to 0 even though it is set to 100 in the settings.ini but putting it back on 100 over the web interface is no problem, the radio still works.
I just don't see anything in my playlist. I am a paying customer for google all access and have no problems with it on my phone.

Any ideas?

regards

**Comment by gferrell** [comment]
Changing the security setting worked for my, but I would rather not reduce the amount of security.  The good thing is that you can enable before booting PI, then disable after connecting to GMusic.  I don't know how long it will stay connected though, so I consider this a workaround.

**Comment by belak** [comment]
Is anyone here still having problems with this? If there isn't a response in a week, I'll close this issue.

**Comment by belak** [comment]
@gferrell I use mopidy-gmusic with 2fa enabled, so I know it's possible. Just use an app password https://support.google.com/accounts/answer/185833?hl=en
