### ISSUE TITLE
support caching of tracks/artists/albums/playlists for quicker loading

### ISSUE THREAD

**Issue by jaapz** [mopidy/mopidy-gmusic#28]
mopidy-gmusic is great, but takes a lot of time initiaiting the mopidy server probably because it is fetching information on everything in my All Access collection. Would be awesome if it cached some of that information in a local database.

**Comment by jodal** [comment]
This should be somewhat addressed by commit 55e3a2462368b4be47cb024ce40c090ca7ad6508 by @felixb.

**Comment by belak** [comment]
I'm reworking some of the caching on my own... it seems like the biggest pain point right now is related to playlists, as they don't return all the song metadata needed to cache all the songs in that one request.

**Comment by belak** [comment]
The cache rewrite has made it into develop. Library/playlist loading should be fast enough that storing a local library database shouldn't be needed.
