### ISSUE TITLE
crash when adding a new playlist

### ISSUE THREAD

**Issue by woutervanwijk** [mopidy/mopidy-gmusic#31]
When I add a playlist in the Google Music webclient, the Gmusic plugin will crash Mopidy after a while. :(

**Comment by jodal** [comment]
Is this still an issue?

**Comment by jodal** [comment]
As this issue is 17 months old, there's been lots of changes to Mopidy-GMusic since it was reported, and I can see no crashes 10 minutes after adding a new playlist in the Google Play Music web client, I'm closing this. Please open a new issue if this is still a problem.
