### ISSUE TITLE
Calling `get_track_info()` on thumbs up songs

### ISSUE THREAD

**Issue by felixb** [mopidy/mopidy-gmusic#53]
I wanted to fix the fetch of metadata for thumbs up songs (simon-weber/Unofficial-Google-Music-API#283) and realized, we could just call 

```
for song in self.backend.session.get_thumbs_up_songs():
    if not song['deleted']:
        track = self.backend.library._aa_to_mopidy_track(song)
        tracks += [track]
```

This would reduce network IO a lot on startup!

Anyway, the problem is, that there may be some deleted/moved tracks in the playlist (see simon-weber/Unofficial-Google-Music-API#283).

This code would show these deleted (by Google) tracks.
Caching the `Track` (#42) is not a solution. The tracks are not playable.

But calling `get_track_info()` just to check, if the tracks got moved is kind of an overdose.

Any thoughts on that?

**Comment by belak** [comment]
Just some additional notes:

`get_thumbs_up_songs()` doesn't exist any more. There's `get_promoted_songs()` but I don't think those are guaranteed to have a thumbs-up.

**Comment by belak** [comment]
I'm closing this for now, as the startup is improved and we're tracking some playlist improvements (hopefully related to thumbs up) in #136
