### ISSUE TITLE
gmusic/all_access unknown config key

### ISSUE THREAD

**Issue by k2s** [mopidy/mopidy-gmusic#58]
installed with pip on Arch Linux and added all_access=true. now I am getting this warnings in mopidy output:

WARNING  Found gmusic configuration errors, the extension has been automatically disabled:
WARNING    gmusic/all_access unknown config key.
WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.

**Comment by afterthought325** [comment]
I'm not able to get this working either, even after following k2s's command that worked for him.

**Comment by Apokly** [comment]
Same for me, tried all branches ...

**Comment by zegnus** [comment]
After doing 

```
pip install --upgrade git+https://github.com/hechtus/mopidy-gmusic.git@develop
```

Starting mopidy says

```
INFO     Disabled extension gmusic: (pyasn1-modules 0.0.6 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('pyasn1-modules==0.0.5'), set(['oauth2client']))
```
