### ISSUE TITLE
Songs don't scrobble

### ISSUE THREAD

**Issue by 0nse** [mopidy/mopidy-gmusic#60]
I'm using mopidy-gmusic from the current development branch together with [mopidy-scrobbler](https://github.com/mopidy/mopidy-scrobbler). The scrobbler works for local files but not for tracks played through mopidy-gmusic.

As the scrobbler is correctly transmitting the "Now playing" information, I would guess this is a problem on the gmusic side. Maybe it doesn't properly tell when a song has been fully played?

**Comment by liftarn** [comment]
Also mentioned at https://github.com/mopidy/mopidy-scrobbler/issues/6

**Comment by jodal** [comment]
Fixed in develop branch, will be part of upcoming 1.0.0 release.
