### ISSUE TITLE
Can't browse tracks, not reacting to tracks

### ISSUE THREAD

**Issue by frdmrckr** [mopidy/mopidy-gmusic#66]
I can't browse through my google music, non-unlimited account, using pi muicbox. I also noticed that the frontend I'm working on doesn't work with the google music. It doesnt seem to be receiving the track playback started command when google music starts

**Comment by jodal** [comment]
Closing since this is nearly a year old. Please open a new issue if you still experience this with the latest develop or the upcoming 1.0.0 release.
