### ISSUE TITLE
Support Songza derived radio stations

### ISSUE THREAD

**Issue by dylanPowers** [mopidy/mopidy-gmusic#68]
I noticed that there isn't support for the Songza derived radio stations. In comparison, the artist and genre stations seem to work fine.
I'm interested in digging into this myself, but if you have any suggestions. Please let me know! :)

**Comment by NonaSuomy** [comment]
Anyone around to reopen this now that it's supported in the gmusicapi?

**Comment by belak** [comment]
I'm not familiar with this feature... Could you provide any background information on this?

**Comment by NonaSuomy** [comment]
https://github.com/simon-weber/gmusicapi/issues/295

https://github.com/simon-weber/gmusicapi/pull/460
https://github.com/simon-weber/gmusicapi/commit/b91febbbd8cc7f5c3b7ee1beddc419cd88b4abad

Basically Google bought the service songza and dropped it in there music service, basically allows any free subscription to listen to songza "situations" radio stations. 

Usually, the station names are based on activities like "relaxing" https://play.google.com/music/listen#/situations/Nujfc6muvmopflrnotbpjhto5ou and situations like "indie dance party" https://play.google.com/music/listen#/wst/situations/Ly2qbctvououx22y5cn2a34y3ku , artists like "Paramore" https://play.google.com/music/listen#/wst/artist/Awioa52yrttxbtc57ged6joexeq names then they give you a bunch of stuff to listen to that are similar artists etc.

it also has a skipping feature built-in for the free accounts, you can skip up to 6 songs per hour on station loads. (Which was also supported by a python kodi addon script) if it helps to figure it out.

https://github.com/foreverguest/repository.foreverguest/blob/master/plugin.audio.googlemusic.exp/plugin.audio.googlemusic.exp-1.11.1.zip

"When you're listening to free radio stations, you can skip up to 6 songs per hour.

When you're nearing your skip limit, you'll see a notification with the option to subscribe to Google Play Music. If you choose to subscribe, you'll get unlimited skips and ad-free access to over 30 million songs."

https://support.google.com/googleplay/answer/6230658?hl=en

Hopefully, they will support more and more locations, if it's not in your current location you could use a service http://alternativeto.net/software/tunnelbear/ I believe there is a free account that lets you tunnel to the USA.

https://wiki.archlinux.org/index.php/TunnelBear

**Comment by NonaSuomy** [comment]
Looks like they call it "Listen_Now" ctrl f here:
http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html

**Comment by NonaSuomy** [comment]
Future reference: https://github.com/simon-weber/gmusicapi/issues/552

**Comment by NonaSuomy** [comment]
Hi again, the code is now in the development branch of gmusicapi if you would like to check it out to see if you can get something going simon-weber/gmusicapi#561 Thank you!

**Comment by belak** [comment]
I've been focusing on other projects, but I'm still around to review pull requests. Also note that I wouldn't merge anything in to gmusic before it's in a released version of gmusicapi though I'd be happy to look at it before then.

**Comment by NonaSuomy** [comment]
Merged into gmusicapi since version 11 for anyone willing to add support!
References [gmusic issue 552](https://github.com/simon-weber/gmusicapi/issues/552#issuecomment-413387085) seems this project was able to utilize it so far if it helps: [tizonia-openmax-il](https://github.com/tizonia/tizonia-openmax-il/issues/473)

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
