### ISSUE TITLE
Caching user playlists locally

### ISSUE THREAD

**Issue by BlackLight** [mopidy/mopidy-gmusic#71]
By now loading user playlists by looking up all the tracks from GMusic is a very, extremely slow operation. In my case I have something like 20000 tracks in my playlists and this can really take up to 20 minutes for having mopidy+gmusic up & running. Wouldn't it be a good idea to cache trackIDs -> info locally, so we don't have to perform the GMusic lookup every time?

**Comment by jaapz** [comment]
+1 this would be great to have

**Comment by berot3** [comment]
duplicate of #28

**Comment by jaapz** [comment]
@berot3 oh, I forgot I already reported that issue :P

**Comment by jodal** [comment]
Closing as duplicate of #28.
