### ISSUE TITLE
Stop doesn't change Mopidy state

### ISSUE THREAD

**Issue by morgoth** [mopidy/mopidy-gmusic#77]
When using "stop" on gmusic song, Mopidy is still in "playing" state.
There is no music, as it somehow stopped playing, but the state is invalid.
I have no such issue when stopping song from local backend.
For the background how I found this issue you can see https://github.com/mopidy/mopidy.js/issues/5

**Comment by jodal** [comment]
I'm quite confident that this was fixed as a side effect of 7652f25f4f6850e0440719f95e0e68d9545ee83e.

**Comment by jodal** [comment]
To be a bit more verbose: Previously, the `GMusicPlaybackProvider.stop()` method was overridden. It is no longer changed in any way, and should work identical to stop in any other Mopidy backend.
