### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by kraiz** [mopidy/mopidy-gmusic#79]
Thanks for your work. I'm using this extension at home and it's great to let party guests search and play the music out of my google all access account. 

I set up mopidy at work too but run into trouble. I get some Timeout/"Read zero bytes" exceptions about 2 minutes after starting mopidy. It looks like the communication with the google servers don't go via proxy. I set up environment variables and defined the proxy in the `mopidy.conf` but both don't change anything.

Tested against current git master versions of `mopidy` and `mopidy-gmusic`.

Is communication via proxy a missing feature or am i running into a bug here? In both cases i'm willing to help with detailed reports and/or PR.

**Comment by jodal** [comment]
Proxy support is entirely missing from Mopidy-GMusic.

**Comment by jodal** [comment]
I dug a bit into the gmusicapi code and opened an issue (simon-weber/gmusicapi#366) requesting access to their Requests session so we can setup proxying properly. The issue also documents a workaround which we can use to fix this if gmusicapi doesn't get there first.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
