### ISSUE TITLE
Support adding Google Music's share links to tracklist

### ISSUE THREAD

**Issue by brandonsturgeon** [mopidy/mopidy-gmusic#80]
I'd like to preface this by saying I'm not very familiar with this whole thing, so please point me in the right direction if this isn't the place to ask.

I'm using the latest development build of mopidy-gmusic

I'm using a chat-based bot to control Mopidy running on a server. I do this by sending it json. For example, to start playing a YouTube video, I'd do `{"jsonrpc": "2.0", "id": 1, "method": "core.tracklist.add", "params": {"tracks": null, "at_position": null, "uri": null, "uris": ["yt:https://www.youtube.com/watch?v=dQw4w9WgXcQ"]}}` where the "yt:" prefixes the youtube video URL. And to play SoundCloud, I'd prefix the URL with `sc:`

I've tried prefixing with `gmusic:` `gm:` `googlemusic:` with no luck. Also what URL do I give it for a public playlist? Because it seems like there are 2 that I could give it. The link I get when I click "get link"  (eg: http://puu.sh/hsWkc/1c0013ae17.png ) on a playlist, or the link I get after I click on "Listen" from the "get link" page (eg: http://puu.sh/hsWnU/dc3fdc3953.png ) but then there's still the "Start Radio" button. I'd assume mopidy-gmusic would take care of that?

Anyway, some guidance would be greatly appreciated. Sorry again if this isn't the right place to ask.

**Comment by jodal** [comment]
The currently supported URIs for Mopidy-GMusic includes:

- `gmusic:track:<track_id>`
- `gmusic:album:<album_id>`
- `gmusic:artist:<artist_id>`
- `gmusic:radio:<station_id>`, e.g. `gmusic:radio:IFL`

Only the track/album/artist URIs are supported by Mopidy-GMusic's `library.lookup()` method, so those are the ones you can successfully give to Mopidy's `tracklist.add()` method.

Mopidy-GMusic could surely learn to understand share links from the Google Music clients, either with a `gmusic:` or without, which will work when mopidy/mopidy#696 is implemented.

**Comment by belak** [comment]
Hey, it looks like your puu.sh links are dead. Any chance you could give another example? Would you just like to be able to take a link from the frontend and add it as either a track or a playlist, or am I misunderstanding?

**Comment by belak** [comment]
I assume you're looking to take the share links and dump them into that rpc interface?

So, something like gmusic:https://play.google.com/music/m/T3e5zt6k44g4g3ggwzlu2sz2kre ?

**Comment by brandonsturgeon** [comment]
It seems like the Google Music interface has changed since I posted this. I'm not 100% sure what those puushes were showing, but I was mainly just looking for:

A. Which links I can use in this interface
B. How to prefix the links so that it understands them

And I think you answered both of my questions :)

Thanks for parsing through my question, it wasn't worded very well!
