### ISSUE TITLE
Playlists empty

### ISSUE THREAD

**Issue by nielsk** [mopidy/mopidy-gmusic#95]
mopidy won't list my playlists from gmusic anymore. The stuff in library (artists/album/radios) all work fine but my playlists are not shown. Any ideas what the reason could be?

**Comment by dvereber** [comment]
I am also experiencing empty playlists.  I've spent awhile going through the various logs, and can't get to the bottom of it, so I'm posting here in the hopes that someone can send me in the right direction.

>root@musicpi:~# mopidy --version
>Mopidy 1.1.1

>gmusicapi version: 7.0.1-dev

>mopidy-gmusic is also the most recent dev 

I can see the two playlists that in ncmpcpp but, they seem to be empty

run from console, mopidy -v returns the following lines over and over again:

  Request from [127.0.0.1]:39460: listplaylistinfo "PumpedHits"
DEBUG    2015-09-20 22:07:52,174 [3343:MpdSession-14] mopidy.mpd.session
  Response to [127.0.0.1]:39460: OK
DEBUG    2015-09-20 22:07:52,187 [3343:MpdSession-14] mopidy.mpd.session
  Request from [127.0.0.1]:39460: idle
DEBUG    2015-09-20 22:07:52,692 [3343:MpdSession-14] mopidy.mpd.session
  Request from [127.0.0.1]:39460: noidle
DEBUG    2015-09-20 22:07:52,698 [3343:MpdSession-14] mopidy.mpd.session
  Response to [127.0.0.1]:39460: OK
DEBUG    2015-09-20 22:07:52,705 [3343:MpdSession-14] mopidy.mpd.session

**Comment by jodal** [comment]
I believe I had this issue myself, but after various (unrelated?) changes to Mopidy-GMusic my single playlist works nicely.

Can you reproduce this with the latest from Mopidy-GMusic's develop branch?

**Comment by jodal** [comment]
Please open a new issue if this is still an issue with the latest develop version.
