### ISSUE TITLE
Google Play doesn't count

### ISSUE THREAD

**Issue by pattyco** [mopidy/mopidy-gmusic#96]
We use to put random playlist in our business, and from time to time we delete from that list the ones that haver more plays ( playlists of more than 8 hours) But in the last month we see yesterday that it didn't count any play at the google music website (we only use now Mopidy conected directly to our audio instalation) , but if we do it from the browser it works in real time! :S
Any clue?
In the old versions of Chrome you have the same issue, so maybe it has relation with the versions o gmusic or something
Thanks!

**Comment by jodal** [comment]
I believe this might have the same root cause as #60.

**Comment by jodal** [comment]
Fixed in develop branch, will be part of upcoming 1.0.0 release.
