### ISSUE TITLE
No distributions at all found for modipy-gmusic

### ISSUE THREAD

**Issue by dvereber** [mopidy/mopidy-gmusic#97]
Hello all, I'm trying to get Mopidy-Gmusic installed on my Raspberry pi running the latest raspbian distro, and here is what happens:

I attemtpted to google "No distributions at all found for modipy-gmusic" but got no response, should I have some archive added somewhere?

I am running pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

Is there an alternate installation method aside from pip?

>pip install modipy-gmusic
>Downloading/unpacking modipy-gmusic
>  Could not find any downloads that satisfy the requirement modipy-gmusic
>No distributions at all found for modipy-gmusic
>Storing complete log in /home/pi/.pip/pip.log

====== pip.log says.... ======

------------------------------------------------------------
>/usr/bin/pip run on Sat Aug 29 22:34:07 2015
>Downloading/unpacking modipy-gmusic
>
 > Getting page http://pypi.python.org/simple/modipy-gmusic
>  Could not fetch URL http://pypi.python.org/simple/modipy-gmusic: HTTP Error 404: Not Found
>  Will skip URL http://pypi.python.org/simple/modipy-gmusic when looking for download links for >modipy-gmusic
>  Getting page http://pypi.python.org/simple/
>  URLs to search for versions for modipy-gmusic:
>  * http://pypi.python.org/simple/modipy-gmusic/
>  Getting page http://pypi.python.org/simple/modipy-gmusic/
>  Could not fetch URL http://pypi.python.org/simple/modipy-gmusic/: HTTP Error 404: Not Found
>  Will skip URL http://pypi.python.org/simple/modipy-gmusic/ when looking for download links for >modipy-gmusic
>  Could not find any downloads that satisfy the requirement modipy-gmusic
>
>No distributions at all found for modipy-gmusic
>
>Exception information:
>Traceback (most recent call last):
>  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
>    status = self.run(options, args)
>  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
>    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
>  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 978, in prepare_files
>    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
>  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 157, in find_requirement
>    raise DistributionNotFound('No distributions at all found for %s' % req)
>DistributionNotFound: No distributions at all found for modipy-gmusic

**Comment by jodal** [comment]
It is "mopidy-gmusic", not "modipy-gmusic".
